### ISSUE TITLE
Item 1. 가변성을 제한하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#1]
Item 1. 가변성을 제한하라를 읽고 정리해서 코멘트로 남겨주세요.

**Comment by pkch93** [comment]
**_가변성은 코드 관리를 어렵게 만드므로 제한해야한다._**
- 상태를 적절하게 관리하는 것은 어렵다.
- 상태를 갖는 부분에 대한 이해가 필요하며 상태 변경이 많아지면 추적이 힘들다.
- 코드의 실행을 추론하기 어렵다.
- 멀티스레드 환경에서는 적절한 동기화가 필요하다.
- 테스트하기 어렵다.
- 하스켈과 같은 특정 프로그래밍 언어는 가변성을 최대한 제한하기도 한다.

위 이유로 가변성에 대한 일관성 문제와 복잡도 증가 때문에 가변성을 적절히 제한하는 것이 좋다.

**_코틀린에서는 가변성을 제한하는 여러 도구들을 지원한다._**
- 읽기전용 프로퍼티 `val`을 통해 변경 불가능한 상태를 관리하도록 만들 수 있다.
- 리스트, 집합, 맵과 같이 특정 객체를 담은 컬랙션들도 변경 불가능한 컬랙션을 만들 수 있도록 지원한다.
- 데이터 클래스의 copy는 손쉽게 불변 객체를 만들 수 있도록 지원한다.
- 그밖에 외부에 노출될 필요가 없는 상태는 private으로 감추어 가변성을 제한할 수 있다.

**_자바와의 차이점_**
- `final` 키워드로 가변성을 제한하는 자바와 달리 코틀린은 `val`을 사용한다.
- 패키지, 모듈 단위의 접근제한자 `modifier`가 없는 자바와 달리 코틀린은 `internal` 접근제한자가 있어 보다 활용도가 높다고 생각한다.
  - 단, Java 9 부터는 모듈화를 지원한다. (하지만 써본적이 없..)

**Comment by aegis1920** [comment]
### 가변성을 제한하자

- 프로그램을 이해하고 디버깅하기 힘들어진다
- 시점에 따라 값이 달라질 수 있으므로 코드의 실행을 추론하기 어려워진다
- 멀티스레드 프로그램이라면 적절한 동기화가 필요하다
- 모든 상태를 테스트해야하므로 테스트가 어려워진다

하스켈 같은 순수 함수형 언어에서는 가변성을 완전히 제한하기도 한다.

### 코틀린에서 가변성 제한하려면?

- 읽기 전용 프로퍼티인 val로 선언
- 읽기 전용 컬렉션 사용
- data class의 copy 함수 사용

List 인터페이스는 읽기 전용 인터페이스. mutableList로 선언 후, add와 get이 호출하는 게 다르다.

### immutable 객체를 사용하면 얻을 수 있는 장점

- 한 번 정의된 상태가 유지되므로 이해하기 쉬움
- 공유되어도 상관없으므로 병렬 처리에 유용
- 참조가 변경되지 않으므로 쉽게 캐시 가능
- Set 또는 Map의 Key로 사용할 수 있음

### 정리 및 내 생각

- 변할 수 있는 성질을 가지고 있다는 것 자체만으로 그 관계를 이해해야되며 추적해야된다는 뜻이 된다.
- 가장 좋은 건 상태(필드)를 가지지 않는 것이라고 생각함
- 만약 필드를 가지면 최대한 불변으로 만들자
- 필드를 변경할 일이 생길 때 set을 하게 되는 경우가 많은데 새로 생성하자

**Comment by hyenny** [comment]
## 코틀린에서 가변성을 제한하는 세가지 방법

### 읽기 전용 프로퍼티(val)

- val ⇒  값(value)처럼 동작
- 일반적인 방법으로는 값이 변하지 않는다.
- 그렇다고 읽기 전용 프로퍼티가 완전히 변경 불가능한 것은 아니다.
    - mutable 객체를 담고 있다면 내부적으로 변경할 수 있음

### 가변 컬렉션과 읽기 전용 컬렉션 구분하기

- 읽고 쓸 수 있는 컬렉션(가변 컬렉션)
- mutable이 붙은 인터페이스는 대응되는 읽기 전용 인터페이스를 상속 받아서, 변경을 위한 메서드를 추가한 것
- ex. MutableLsit<T>
    - List<out T>
    - MutableCollection<T>
- 읽기 전용 컬렉션
- 컬렉션 다운 캐스팅 금지
    - 읽기 전용 컬렉션을 mutable 컬렉션으로 다운캐스팅하면 안된다.
    - 만약 읽기 전용에서 mutable로 변경해야 한다면 복제(copy)를 통해 새로운 mutable 컬렉션을 만들면 된다. (`list.toMutableList()`)
- 가변 컬렉션을 외부에 노출하지 말고, 복제한 가변 컬렉션(방어적 복제)을 반환하거나 읽기전용 슈퍼타입으로 업캐스트(가변성 제한)해서 반환한다.
### 데이터 클래스의 copy

- data 한정자를 붙인 class에는 copy() 메서드가 기본으로 정의되어 있다.
    - copy는 모든 기본 생성자 프로퍼티가 같은 새로운 객체(immutable)를 생성한다.
    
### 느낀점 & 생각

- ‘프로퍼티를 읽을 수만 있다는 속성(읽기 전용)’과 ‘값이 변할 수 없는 것(가변성)’은 구분해서 생각해야 한다.’
    - val에 mutableList를 정의하면 값이 변경될 수 있다는 걸 알았음에도 val = 불변 이라고 생각했다. 읽기 전용과 가변성의 차이를 구분해야겠다.
- 객체 안에 객체 타입 필드가, 그 안에 또 객체 필드가 있을 경우 중간 객체에 변경을 적용해야 할 때가 생긴다. 이 때 불변을 유지하기 위해 copy를 객체마다 계속 쓰게 되는데 이게 맞는지 의문이 들 때가 있다. java도 setter를 제한하면 생길 문제인데 다 복제해서 사용하는지 궁금…
