### ISSUE TITLE
Item 10. 단위 테스트를 만들어라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#10]
`Item 10. 단위 테스트를 만들어라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by aegis1920** [comment]
### 내 생각

- 제목이 곧 내용
- 단위 테스트의 장점이나 단점, TDD등 알고있지만 쉽지 않은 현실. 다들 어떻게 하고있는지 궁금

**Comment by pkch93** [comment]
**_단위 테스트를 만들어라_**

> 위 요약으로 모든걸 설명할 수 있을거 같다.
>
> 코틀린 보다는 단위 테스트에 대한 포멀한 내용들이라서 한번쯤 읽어보면 되지 않을까 싶음.
