### ISSUE TITLE
Item 11. 가독성을 목표로 설계하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#11]
`Item 11. 가독성을 목표로 설계하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
> 개발자가 코드를 작성하는 데는 1분이 걸리지만, 이를 읽는 데는 10분이 걸린다.
> 
> - 로버트 마틴 (클린코드 저)

로버트 마틴의 말처럼 개발자는 어떤 코드를 작성하는 것보다 읽는데 시간을 많이 소모한다. 때문에 보다 가독성을 생각하면서 코드를 작성하면 읽는데 사용하는 시간을 줄일 수 있다.

# 가독성에 영향을 끼치는 요소

## 경험

이런 가독성은 사실 사람마다 다르게 느낄 수 있다.

```kotlin
if (person != null && person.isAdult) {
	view.showPerson(person)
} else {
	view.showError()
}
```

```kotlin
person?.takeIf { it.isAdult }
			?.let(view::showPerson)
			?: view.showError()
```

위 두 코드 중 어떤 코드가 더 잘 읽힐까? 전자는 어떤 프로그래밍 언어를 사용했던 잘 읽힌다. 후자는 일단 읽고 이해하기 어렵다. 후자의 코드를 한눈에 이해하기 위해서는 `takeIf`, `let`와 elvis 연산자를 이해하고 있는 숙련된 코틀린 개발자여야 할 것이다.

또한 전자의 코드는 쉽게 수정/디버깅이 가능하지만 후자는 그렇지 못하다.

## 극단적인 코틀린 활용

특정 기능에 매몰되어 극단적으로 활용하지는 않아야한다.

```kotlin
students
	.filter { it.result >= 50 }
	.joinToString(separator = "\n") {
		"${it.name} ${it.surname}, ${it.result}"
	}
	.let(::print)

FileInputStream("file.gz")
	.let(::BufferedInputStream)
	.let(::ZipInputStream)
	.let(::ObjectInputStream)
	.readObject() as SomeObject
```

위 코드들은 디버그가 힘들고 특히 경험이 적은 코틀린 개발자들은 이해하기 어렵다.

## 컨벤션

사람에 따라서 가독성에 대한 관점이 다르다. 따라서 보통의 경우 프로그래밍 언어의 표준 컨벤션을 따라야한다. 언어의 표준 컨벤션을 따르면 해당 언어를 사용하는 대부분의 개발자들은 보다 쉽게 코드를 이해할 수 있다.

여기에 더불어서 팀에서 정의한 컨벤션을 정의한다면 보다 팀 내 프로젝트 코드를 이해하기 쉬울 것이다.

**Comment by aegis1920** [comment]
- 가독성은 사람마다 다르게 느낄 수 있습니다. 뇌는 기본적으로 짧은 코드를 빠르게 읽을 수 있겠지만, 익숙한 코드는 더 빠르게 읽을 수 있습니다.
- 프로그래밍은 쓰기보다 읽기가 중요하다는 의미입니다.
- 숙련된 개발자만을 위한 코드는 좋은 코드가 아닙니다.  (꽤 일반적으로 사용되는 관용구, ?., takeIf, let을 쓴다고 하더라도 != null로 쓰는 게 더 이해하기 쉽다면 != null로 사용하기)

```
// 구현 A
if (person != null && person.isAdult) {
  view.showPerson(person)
} else {
  view.showError()
}

// 구현 B
person?.takeIf { it.isAdult }
  ?.let(view::showPerson)
  ?: view.showError()
```

구현 A가 훨씬 직관적이다.

**Comment by rockjoon** [comment]
```kotlin
students
   .filter { it.result >= 50 }
   .joinToString(separator = "\n") {
      "${it.name} ${it.surname}, ${it.result}"
    }
   .let(::print)
   ```
   이러한 코드가 안좋은 코드라고 생각해본 적 없다.
   이미 너무 많이 사용되는 방식의 코드라서 그런걸까?
 
 책에서는 다음의 이유로 비용이 발생하는 코드이지만 감당할만한 비용이라고 한다.
1. 경험이 적은 개발자가 이해하기 어렵다.    -->  이게 문제일까?라는 생각도 든다.
2. 디버그가 힘들다.                          -->  함수형 프로그래밍의 어쩔수 없는 단점인 것 같다...


 
 개인적으로는 이를 일반적인 명령형으로 작성할 때의 코드량을 생각하면 이런 방식을 쉽게 포기하기 힘들다.

**Comment by cmg1411** [comment]
# let 을 잘 쓰지 말자.
- `?.let {} ?: ~` 보단 `if-else` 가 낫다.
  - let 은 연산결과를 반환한다. 앞의 파라미터가 null 인 경우 뿐만 아니라 let 람다식의 결과가 Null 일 때에도 ~ 가 실행된다.
  - 읽기 쉽다. 디버깅하기 쉽다. 수정하기 쉽다. 

# let 을 잘 쓰자.
- 안전호출 할 때. (특히 var 는 if-else 에서는 스마트 캐스팅이 되지만, ?.let 은 된다)
- 아규먼트 이후로 연산을 넘길 때.
- 래퍼런스를 랩핑할때.

<br>

```agsl
지금까지 코틀린 코드로 몇줄 줄이면 더 잘 짠 코드라고 생각했다.
억지로 줄이는 것은 오히려 가독성을 떨어뜨린다.
또, apply, let, run, with, also, takeIf 등 코틀린이 마련해놓은 편한 것들은
동작을 잘 알고 쓰는게 중요하겠다.
```
