### ISSUE TITLE
Item 12. 연산자 오버로드를 할 때는 의미에 맞게 사용하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#12]
`Item 12. 연산자 오버로드를 할 때는 의미에 맞게 사용하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
연산자 오버로딩은 매우 강력한 기능이지만 잘못 구현을 하면 예상치 못한 버그를 야기할 수 있다.

```kotlin
fun Int.factorial(): Int = (1..this).product()
```

다음과 같이 팩토리얼을 구하는 확장함수가 있다. 팩토리얼은 수식으로 `6!`과 같으므로 `!`를 통해 표현하고 싶다. 따라서 `!` 동작을 표현하는 `not`을  다음과 같이 재정의할 수 있다.

```kotlin
operator fun Int.not() = factorial()
```

그러면 `!6`과 같이 팩토리얼을 표현할 수 있다.

단, 위 코드는 처음 본 개발자들에게는 혼란을 야기할 수 있다. 일반적으로 프로그래밍 언어에서 `!`는 논리연산에서 사용하는 부정의 의미이기 때문이다. 또한 `not`이라는 함수의 이름에도 맞지않다.

따라서 연산자 오버로드를 사용할 때는 오해의 여지가 없도록 의미에 맞게 정의해야한다. 의미가 명확하지 않다면 infix 함수를 정의하는 것이 좋다.

> [infix function](https://www.notion.so/infix-function-3814c035985546368ee9d6e056ef76e8)
>
> [연산자 오버로드](https://kotlinlang.org/docs/operator-overloading.html)

# 규칙을 무시해도 되는 경우

앞선 연산자 오버로딩 규칙을 무시해도 되는 유일한 경우가 있다. 바로 DSL을 설계할 때이다.

```kotlin
body {
	div {
		+"Some text"
	}
}
```

위와 같이 HTML용 DSL에서 `"Some text"`에 `+`로 `String#unaryPlus`가 사용되었다. 이렇게 사용될 수 있는 이유는 위 코드가 DSL 코드이기 때문이다.

**Comment by aegis1920** [comment]
- 연산자 오버로딩은 그 이름의 의미에 맞게 사용해 주세요
- 의미가 명확하지 않다면 infix를 활용한 확장 함수를 사용해도 됩니다

**Comment by rockjoon** [comment]
연산자 오버로드는 가급적이면 사용하지 않는 편이 좋다고 생각한다.  
해당 코드에서만 통용되는 규칙을 만드는 것은 해석하기 어려운 코드를 만들기 때문이다.  
필요한 경우에는 이름이 있는 확장 함수를 사용하는 것이 더 좋은 것 같다

**Comment by cmg1411** [comment]
# 연산자 오버로딩은 의미에 맞게 사용하자.
- 코틀린은 연산자 오버로딩이 허용되지만, 각각의 의미에 맞게 사용해야한다.
- infix function 은 가독성에 도움을 줄 수 있다. 연산자 오버로딩 했을때 의미전달이 모호하다면, infix function 을 사용하자.

```agsl
infix function 은 컴파일타임에 일반 함수로 변환되므로, 런타임에 코스트는 없다.
```
