### ISSUE TITLE
Item 13. Unit?을 리턴하지 말라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#13]
`Item 13. Unit?을 리턴하지 말라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
`Unit?`와 `Boolean` 타입은 서로 바꿔서 리턴할 수 있다. `Boolean`은 true 또는 false 둘 중 하나로 리턴되는 반면 `Unit?`는 Unit 또는 null로 리턴할 수 있기 때문이다.

```kotlin
fun isCorrect(key: String): Boolean = // ...

if (!isCorrect(key)) return
```

```kotlin
fun verify(key: String): Unit? = // ...

verify(key) ?: return
```

위와 같이 `Boolean`으로 리턴하는 것을 `Unit?`에서 처리하는 방식으로 변경할 수 있다. 하지만 `Unit?` 사용은 코드의 가독성을 떨어뜨리며 오해의 소지를 만들 수 있다.

```kotlin
getData()?.let { view.showData(it) } ?: view.showError()
```

위 코드처럼 `?`가 많이 들어간 코드는 한눈에 봤을때 이해하기 어렵다. 위 상황에서 `view#showError`가 호출되는 경우는 `getData`가 null이거나 `view#showData`의 결과가 null인 경우이다. 여기서 `getData`가 null이 아닌 경우는 `showData`와 `showError`가 함께 호출된다. 때문에 얼핏봐서는 `showError` 만 호출되는 것으로 볼 수 있기 때문에 이해하기 어렵다.

위와 같은 코드는 if-else 문으로 푸는게 차라리 가독성이 좋다.

```kotlin
if (data != null) {
	view.showData(data)
} else {
	view.showError()
}
```

위 경우는 `Unit?`과 `Boolean`에도 동일하게 적용할 수 있다. `Unit?`는 오해를 불러오기 쉬우므로 기본적으로 `Unit?` 사용은 자제하는 것이 좋다.

**Comment by aegis1920** [comment]
- Unit?을 Boolean처럼(Unit or null) 사용하지 말라

**Comment by cmg1411** [comment]
# Unit? 는 쓸일이 없다.
- Unit 또는 null 을 반환 한다는 말이다.
  - 처리하는 쪽에서는 ?: 같은 널 처리로 처리 할 것이다.
- `Boolean 의 true/false` 와 `if-else` 로 대체될 수 있다. 이게 더 읽기 쉽다.
- Item11 의 주제와 비슷하다. 코틀린스럽다는 이유로 Unit? 과 ?: 조합을 쓰는건 지양하자. 읽기 더 어렵다.

```agsl
그냥 Unit? 쓰지말자.
```
