### ISSUE TITLE
Item 14. 변수 타입이 명확하지 않은 경우 확실하게 지정하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#14]
`Item 14. 변수 타입이 명확하지 않은 경우 확실하게 지정하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
코틀린은 강력한 타입 추론을 지원한다. 이는 개발 시간을 줄여주며 코드가 짧아지므로 코드의 가독성이 향상될 수 있다. 하지만 타입이 명확하지 않는 경우에 남용하게 되면 가독성을 해칠 수 있다.

```kotlin
val data = getSomeData()
```

위 예시 코드에서는 타입을 드러내지 않고 숨기고 있다. 가독성을 위해서 코드를 설계할 때 읽는 사람에게 중요한 정보는 감춰서는 안된다. **`함수 정의를 보면서 타입 확인하면 안되나?` 라는 의문이 있을 수 있지만 이는 코드의 가독성이 낮다는 의미이다.**

때문에 위와 같은 코드에 타입을 지정해주면 가독성이 높아진다.

```kotlin
val data: UserData = getSomeData()
```

**Comment by aegis1920** [comment]
- public하게 공개되어있는 경우 타입을 명확하게 지정하자
- 변수 타입은 상황에 따라 명확하지 않은 경우 지정하자.

**Comment by cmg1411** [comment]
# 변수 타입이 명확하지 않다면 지정하자.

- Item3 의 내용처럼, 코틀린의 타입추론이 다형성 사용에서 안전하지 않는 결과를 낼 수 있다.
- 인텔리제이에서 타입을 지정해주지만, 읽는 사람이 Github 에서 읽을지, 이클립스를 사용할지 알 수 없다.
- (타입이 보이지 않는 곳에서 타입 없이 보는 것 보단) 타입이 명시되어 있는게 읽기가 쉽다.

```agsl
Item3 내용과 같이 안전성에 문제가 있을 수 있으니 타입 지정하자는건 인정.

가독성에서는, 우리 조직에서는 모두 intelliJ 사용하는데 굳이..? 라는 생각으로 동의 못하다가

코드리뷰에서는 도움 크게 되겠다는 것에 동의함.
```
