### ISSUE TITLE
Item 15. 리시버를 명시적으로 참조하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#15]
`Item 15. 리시버를 명시적으로 참조하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
무언가를 더 자세하게 표현하기 위해 명시적으로 긴 코드를 사용할 때가 있다. 대표적으로 함수와 프로퍼티를 지역 또는 톱레벨 변수가 아닌 다른 리시버로 가져온다는 것을 나타낼 때이다.

```kotlin
class User: Person() {
	private var beersDrink: Int = 0
	
	fun drinkBeers(num: Int) {
		// ...
		this.beerDrink += num
		// ...
	}
}
```

위 예시에서 `this`가 해당 클래스의 메서드라는 것을 표현하는 리시버이다.

클래스의 리시버처럼 확장 함수의 리시버도 명시적으로 참조할 수 있다. 아래 예시는 리시버를 명시적으로 표현하지 않은 퀵소트 구현이다.

```kotlin
fun <T: Comparable<T>> List<T>.quickSort(): List<T> {
	if(size < 2) {
		return this
	}
	val pivot = first()
	val (smaller, bigger) = drop(1).partition { it < pivot }
	return smaller.quickSort() + pivot + bigger.quickSort()
}
```

반면 리시버를 명시적으로 표현하면 아래와 같다.

```kotlin
fun <T: Comparable<T>> List<T>.quickSort(): List<T> {
	if(size < 2) {
		return this
	}
	val pivot = this.first()
	val (smaller, bigger) = this.drop(1).partition { it < pivot }
	return smaller.quickSort() + pivot + bigger.quickSort()
}
```

`first`와 `drop` 호출시 `this` 리시버를 참조했다. 이를 통해 `first`와 `drop`이 `List`의 메서드를 호출한 것으로 명시적으로 확인할 수 있다.

스코프 내부에 둘 이상의 리시버가 있는 경우라면 리시버를 명시하는 것이 더더욱 가독성에 좋다. 특히 apply, with, run 함수를 사용할 때가 대표적인 예이다.

```kotlin
class Node(val name: String) {
	fun makeChild(childName: String) = create("$name.$childName").apply { print("Created ${name}") }

	fun create(name: String): Node? = Node(name)
}

fun main(args: Array<String) {
	val node = Node("parent")
	node.makeChild("child")
}
```

위 결과를 예측해보면 `"Created parent.child"`가 콘솔에 찍힐 것으로 예상된다. 하지만 실제로는 `"Created parent"`만 찍힌다.

```kotlin
class Node(val name: String) {
	fun makeChild(childName: String) = 
				create("$name.$childName")
					.apply { print("Created ${this.name}") } // 컴파일 에러

	fun create(name: String): Node? = Node(name)
}
```

`apply` 내부에서 `this.name`를 참조하면 컴파일 에러가 발생한다. 이는 `apply`를 호출하는 `create` 함수의 리턴타입이 `Node?`이기 때문이다. null이 될 수도 있으므로 코틀린 컴파일러는 컴파일 에러를 던진다. 따라서 다음과 같이 언팩 후 참조해야한다.

```kotlin
class Node(val name: String) {
	fun makeChild(childName: String) = 
				create("$name.$childName")
					.apply { print("Created ${this?.name}") } // OK

	fun create(name: String): Node? = Node(name)
}
```

위와 같이 호출하면 예상했던대로 `"Created parent.child"`가 콘솔에 찍힌다.

참고로 위 `apply` 사용은 잘못된 사용 예시이다. `also`와 파라미터 `name`을 사용했다면 위와 같은 문제 자체가 일어나지 않는다. 그리고 `also`는 명시적으로 리시버를 지정하게되므로 일반적으로는 also 또는 let을 사용하는 것이 nullable 값을 처리할 때 좋은 선택지가 된다.

```kotlin
class Node(val name: String) {
	fun makeChild(childName: String) = 
				create("$name.$childName")
					.also { print("Created ${it?.name}") }

	fun create(name: String): Node? = Node(name)
}
```

만약 리시버가 명확하지 않다면 리시버를 명시적으로 적어 표시할 수 있다. 레이블 없이 리시버를 사용하면 가장 가까운 리시버를 뜻한다.

```kotlin
class Node(val name: String) {
	fun makeChild(childName: String) = 
				create("$name.$childName")
					.apply { print("Created ${this?.name} in ${this@Node.name}") }

	fun create(name: String): Node? = Node(name)
}
```

`this@Node`로 어떤 리시버를 사용하는지 더욱 명확해졌다. 이를 통해 코드를 안전하게 작성하면서 가독성도 향상시킬 수 있다.

# DSL 마커

코틀린 DSL 사용시에는 여러 리시버를 가진 요소들이 중첩되더라도 리시버를 명시적으로 붙이지 않는다. DSL은 원래 그렇게 사용하도록 설계되었기 때문이다.

다만, DSL에서는 외부의 함수를 사용하는 것이 위험한 경우가 있다. 암묵적으로 외부 리시버 사용을 막기 위해서는 `@DslMarker` 메타 어노테이션을 사용해서 컴파일러의 도움을 받을 수 있다.

**Comment by aegis1920** [comment]
- this가 여러 곳에서 사용되는 경우, 명시적으로 this를 작성하자 (apply, with, run 등등..)
- 일반적으로 also 또는 let을 사용하는 것이 nullable 값을 처리할 때 훨씬 좋은 선택지

**Comment by rockjoon** [comment]
```kotlin
//apply 사용
fun makeChild(childName: String) =
    create("$name.$childName")
        .apply { print("Created ${this?.name}")}

//also 사용
fun makeChild(childName: String) =
    create("$name.$childName")
        .apply { print("Created ${this?.name}")}
```

apply와 also를 사용할 때 개인적으로 그 이름에서 오는 시멘틱에 집중하는 편이다.  
apply는 객체 자체를 파라미터로 받기 때문에 코드가 객체 내부에서(apply) 상호작용 하는 느낌이고  
also는 객체를 리시버로 받기 때문에 코드가 해당 객체와 함께(also) 상호작용하는 느낌을 준다.  

물론 리시버를 명시적으로 적는 것이 가장 명확하긴 하다.

**Comment by cmg1411** [comment]
## 리시버 = 수신객체
- 쉽게 말해 this
- 확장함수는 리시버(this)를 사용할 수 있다.

## 리시버를 명시하자
- class 안에 함수가 apply 를 쓰는 경우에 리시버가 모호해진다. (class 의 this 인지, apply 확장함수 수신객체 this 인지)
- 보통 this 를 명시하면 가장 가까운 리시버(apply 일 것)
- 하지만 생략하게 되면 class 의 리시버
- 따라서 헷갈리지 않게 레이블(@)을 포함한 리시버를 지정해주자!

## apply, run, let, with, also
- 위 코틀린 함수는 정의가 모두 다르다.
- apply, run, let, also 는 확장함수로, 리시버를 암시적으로 보낸다. with 은 파라미터로 리시버를 명시적으로 보낸다.
- apply, run 은 확장함수 리시버를 가진 람다 확장함수를 파라미터로 가진다. 따라서 람다블록에서 this 로 확장함수 리시버를 쓸 수 있다.
- let, also 는 확장함수 리시버를 람다 블록에 파라미터로 명시적으로 던진다. `it` 키워드로 확장함수 리시버를 쓸 수 있다.
`이 함수들의 정의를 숙지하고 사용할 필요가 있다`


> 일반적으로 null 값을 처리할 때에는 let, also 가 apply, run 보다 좋은 선택지.
> this? 보다는 it? 이 낫다는 뜻인듯. this? 는 어디의 리시버인지 헷갈려서 this@apply? 이런식으로 적어줘야하니.
