### ISSUE TITLE
Item 16. 프로퍼티는 동작이 아니라 상태를 나타내야 한다.

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#16]
`Item 16. 프로퍼티는 동작이 아니라 상태를 나타내야 한다.`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
Kotlin의 프로퍼티는 Java의 필드와 비슷해보이지만 전혀 다른 개념이다. 일단 프로퍼티는 getter, setter를 가진다. 이때 getter와 setter는 필드를 기반으로 값을 처리한다.

```kotlin
val name: String? = null
		get() = field?.toUpperCase()
		set(value) {
			if (!value.isNullOrBlank()) {
				field = value
			}
		}
```

위와 같이 Kotlin에서는 프로퍼티를 취급하기 때문에 getter와 setter에서 field라는 백킹 필드 `backing field`를 사용하여 접근할 수 있다.

> 참고로 val로 읽기 전용 프로퍼티를 만들때는 field가 만들어지지 않는다.

기본적으로 primary constructor에 정의한 프로퍼티는 getter, setter를 직접 정의할 수는 없지만 이를 기반으로 만든 프로퍼티는 getter, setter를 직접 정의해서 사용할 수 있다. 이를 파생 프로퍼티 `derived property`라고 한다.

위와 같은 특성 때문에 프로퍼티에 필드를 가지지 않아도 된다.

```kotlin
val fullName: String
	get() = "$lastName $firstName"
```

위와 같이 파생 프로퍼티에 getter만 정의할 수도 있다. 그리고 인터페이스에서도 프로퍼티 정의가 가능하다.

```kotlin
interface Animal {
	val name: String
}
```

이는 `name`이 필드가 아닌 프로퍼티이기 때문에 가능한 것이다. 따라서 위 name은 재정의 `override`가 가능하다.

```kotlin
open class Bird {
	// ...
}

class Chicken: Bird() {
	override val name = "chicken"
}

class Duck: Bird() {
	override val name = "duck"
}
```

마찬가지 이유로 프로퍼티 위임도 가능하다.

> 프로퍼티 위임은 [Item 21. 일반적인 프로퍼티 패턴은 프로퍼티 위임으로 만들어라](https://github.com/Meet-Coder-Study/effective-kotlin-study/issues/21) 에서 더 자세히 다룸

이와 같이 Kotlin에서 프로퍼티는 필드가 아닌 접근자를 나타낸다. 프로퍼티 대신 함수를 사용할 수도 있지만 완전히 대체해서 사용하는 것은 좋지 않다. 특히 프로퍼티로 동작을 처리하는 것은 좋지 않다.

```kotlin
val message: String
		get() = when(HttpStatus){
			HttpStatus.OK -> "성공"
			HttpStatus.BAD_REQUEST -> "잘못된 요청입니다."
			HttpStatus.INTERNAL_SERVER_ERROR -> "일시적으로 오류가 발생했습니다."
		}
```

위와 같이 동작을 처리하는 경우는 함수로 구현하는 것이 바람직하다. 원칙적으로 상태를 나타내거나 설정하기 위한 목적으로만 프로퍼티를 사용하는 것이 좋으며 다른 로직을 포함하면 안된다. 만약 프로퍼티를 함수로 정의할 경우 get / set을 접두사로 붙일 수 있다고 생각이 든다면 프로퍼티로 정의해도 괜찮을 것이다.

**Comment by aegis1920** [comment]
- 코틀린의 프로퍼티와 자바의 필드는 다르다
- 프로퍼티는 동작이 아니라 상태를 나타내야 한다
- 프로퍼티는 사용자 정의 세터와 게터를 가질 수 있다.
- field는 프로퍼티의 데이터를 저장해두는 백킹 필드에 대한 레퍼런스다. val을 사용하면 만들어지지 않으며 var를 선언하면 디폴트로 생성된다.
- 게터나 세터의 역할을 파악하자. 함수로 만들 수 있다면 함수로 만드는 것이 더 명확할 수 있다.

**Comment by cmg1411** [comment]
## 코틀린의 프로퍼티
- 자바의 필드와 다르다.
- 프로퍼티 = 필드(코틀린에서는 backing field 라 부름) + getter + setter
- 프로퍼티는 필드가 필요없다.


- (초기화 된) var property = private backing field + getter + setter
- (초기화 된) val property = private backing field + getter
- (초기화 된) private val(var) = private backing field
- (초기화 없는) val + getter = getter (필드 없음)


# 프로퍼티는 사실상 접근자 개념. (함수 개념)
- 인터페이스에 정의, 오버라이드 가능
- 위임 가능
- 확장 프로퍼티 가능

# 프로퍼티에는 동작이 아닌 상태만 get/set 해야 한다.
- 함수를 쓸 때와 프로퍼티의 getter/setter 를 쓸 때를 잘 구분하자.

### 함수가 좋은 경우
- 연산 비용이 O(1) 보다 클 떄.
- 비즈니스 로직이 포함될 때
- 두번 돌리면 다른 결과가 나올때.
- 게터에서 프로퍼티의 상태 변경이 일어날 때.
