### ISSUE TITLE
Item 17. 이름 있는 인자를 사용하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#17]
`Item 17. 이름 있는 인자를 사용하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
Kotlin은 이름을 지정하여 파라미터를 명확하게 만들 수 있다. 이를 이름 있는 아규먼트 `named argument`라고 한다.

```kotlin
val oneToTen = (1..10).joinToString(seperator = ",")
```

물론 변수를 통해 인자의 의미를 부여할수도 있다.

```kotlin
val seperator = ","
val oneToTen = (1..10).joinToString(seperator)
```

하지만 Kotlin에서는 이름 있는 아규먼트를 사용하면 보다 신뢰할 수 있다. 변수를 사용하는 경우는 변수를 잘못 만들 수도 있고 함수 호출시 같은 타입의 인자에 잘못 배치해서 버그를 야기할 수 있다. 이름 있는 아규먼트는 근본적으로 이런 문제를 방지할 수 있기 때문에 보다 신뢰할 수 있다.

이런 점에서 이름 있는 아규먼트는 다음과 같은 장점을 지닌다.

- 이름을 기반으로 값이 무엇을 나타내는지 알 수 있다.
- 파라미터 입력 순서와 상관없어 안전하다.

특히 이름 있는 아규먼트는 다음 상황에서 더욱 추천한다.

- 디폴트 아규먼트
    - 디폴트 아규먼트를 가질때 보통의 경우 함수는 필수 아규먼트와 관련해서 이름을 짓기 때문에 디폴트 아규먼트에 대한 정보가 충분치 않다. 따라서 이름 있는 아규먼트 사용을 추천한다.
- 같은 타입의 아규먼트가 많은 경우
    - 위치를 잘못 입력했을 시 버그를 야기할 가능성이 높으므로 이를 보다 방지하고자 이름 있는 인자를 사용하는 것이 좋다.
- 함수 타입의 파라미터가 있는 경우
    - 단, 마지막 함수 파라미터는 람다로 표현 가능하므로 제외
    - 특히 여러 함수 타입의 파라미터가 있는 경우 함수 구현과 더불어서 매우 헷갈리는 코드가 될 수 있다. 이름 있는 아규먼트를 활용하면 어떤 함수인지 보다 가독성을 높여준다.

> 개인적으로는 인자가 매우 많은 경우에 `보통 3개 이상` 한눈에 어떤 값이 들어가는지 알 수 있기 때문에 이름 있는 아규먼트를 사용하는 것이 좋았다.
>

**Comment by aegis1920** [comment]
- 이름있는 아규먼트를 적절히 사용해라
    - e.g. sleep(timeMilllis = 100) 의 경우, 이름있는 아규먼트를 사용하자. 아주 명확하다.
- 같은 타입이 있는 경우에도 유용하다

**Comment by rockjoon** [comment]
예전에 짧은 코드에 매몰되었을 때에는 아규먼트에 이름을 붙이는 것을 기피하던 때가 있었다.  
그런데 결론적으로는 코드가 짧더라도 가독성은 떨어지는 경험을 했다. 책에서 나온 것처럼 중요 아규먼트에는 이름을 붙이는 것이
코드의 양은 늘더라도 가독성이 훨씬 좋아지는 방법이라고 생각한다.  

또한 함수 타입 파라미터에 이름을 붙이면 디버깅할 때도 도움이 된다.

**Comment by cmg1411** [comment]
### 이름 있는 아규먼트를 쓰면 좋은 경우
- 디폴트 아규먼트
    - 디폴트 아규먼트가 있으면 파라미터가 모호해진다.
- 같은 타입의 파라미터가 많은 경우
    - 타입이 같으면 위치를 잘못 써도 컴파일 에러가 나지 않으므로 명시적으로 지정하자.
- 함수 타입의 파라미터가 있는 경우 (마지막이라서 중괄호 블록으로 뺄 수 있는 경우 제외)
    - 함수 타입의 파라미터가 인자의 마지막이 아니라면 이름 있는 아규먼트를 쓰자.
