### ISSUE TITLE
Item 19. knowledge를 반복하여 사용하지 말라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#19]
`Item 19. knowledge를 반복하여 사용하지 말라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
**knowledge**란 실용주의 프로그래머의 DRY 원칙에서 가져온 개념으로 일반적인 지식과는 다르게 “의도적인 정보”를 나타내는 개념이다. 즉, 프로젝트를 진행할 때 정의한 모든 것을 **knowledge**라고 할 수 있다.

다양한 knowledge 중에서도 프로그램에서 가장 중요한 knowledge를 꼽는다면 아래와 같다.

1. 로직
    
    프로그램이 어떤 식으로 동작하는지와 프로그램이 어떻게 보이는지
    
2. 공통 알고리즘
    
    원하는 동작을 하기 위한 알고리즘

이 둘의 가장 큰 차이점은 시간에 따른 변화이다. 비즈니스 로직은 시간이 지나면서 계속해서 변하지만 공통 알고리즘은 한 번 정의된 이후에는 크게 변하지 않는다. 반면 프로젝트는 끊임없이 변화한다. 모든 것은 변화하기 때문에 이것에 대비해야한다. 이때 가장 큰 적은 반복되어 있는 **knowledge**이다.

따라서 **knowledge** 반복을 줄이는 것이 바람직하다.

**Comment by hyenny** [comment]
### knowledge를 반복하지 말아야 하는 이유 : 모든 것은 변화한다.
> 모든 것은 변화하고, 우리는 이에 대응해야 한다.
- 변화하는 이유
    - 회사가 사용자의 요구 또는 습관을 더 많이 알게 되었다.
    - 디자인 표준이 변화했다.
    - 플랫폼, 라이브러리, 도구 등이 변화해서 이에 대응해야 한다.

변화할 때 가장 큰 적은 knowledge가 반복되어 있는 부분 -> **공통된 부분으로 추출해서 반복 제거**

### 반복처럼 보이지만 다른 knowledge 구분
- 얼핏 보면 knowledge 반복처럼 보이지만 실질적으로 다른 knowledge 여서 추출하면 안된다
- 어떻게 그런 코드를 알 수 있나? : **'함께 변경될 가능성이 높은가? 따로 변경될 가능성이 높은가?'**

### 정리에서 인상깊었던 문장
> 많은 개발자는 ‘Don’t Repeat Yourself’라는 문장을 엄격하게 지키려고 비슷해 보이는 코드는 모두 추출하려는 경향이 있습니다. 극단적인 것은 언제나 좋지 않습니다. 항상 균형이 중요합니다.

**Comment by aegis1920** [comment]
- 여기서 knowledge란 로직과 공통 알고리즘을 말한다. (단순하게 로직이라고만 이해해도 될 것 같다)
    - 비즈니스 로직은 계속 변하지만
    - 공통 알고리즘은 크게 변하지 않는다
- **모든 것은 변화하고 우리는 이에 대비해야한다.**
- 여러 종류의 추상화를 표현할 수 있는 수많은 솔루션이 있으며 이를 활용하면 반복을 줄일 수 있다.
- 두 코드가 같은 knowledge를 나타내는지, 다른 knowledge를 나타내는지는 **"함께 변경될 가능성이 높은가? 따로 변경될 가능성이 높은가?"라는 질문으로 어느정도 결정할 수 있다**
- 이를 위해 단일 책임 원칙을 지켜야 한다 (클래스를 변경하는 이유는 단 한 가지여야 한다)
    - **처음부터 클래스를 구분해서 만들자**

> 함께 변경될 가능성이 있는지 (의존되어있는지) 파악하고 공통 로직으로 빼자
단일 책임 원칙을 지키자 (메서드를 작성할 때 처음부터 클래스로 빼야할 지 생각해보자)

**Comment by cmg1411** [comment]
표현하려는게 다르면 다른 책임 로직이 같더라고 공통으로 쓰면 안된다. 프로퍼티든 함수든 뭐든.
반대로 표현하려는게 전체적으로 같은 것 또는 뭐 변하지 않는 사실 같은 건 헬퍼 클래스, 함수를 만들어서 하나만 제공한다.
표현하려 하는게 다르다면 다른 위치에 관리하는게 좋다. 재사용하려는 유혹이 들지 않도록.
