### ISSUE TITLE
Item 2. 변수의 스코프를 최소화하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#2]
`Item 2. 변수의 스코프를 최소화하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by aegis1920** [comment]
### 정리 및 내 생각

- 제목이 곧 내용
- 가급적 바로 초기화
- 캡처링에서 시퀀스를 활용하는 예제 이해가 안 감.. 코루틴이라 디버깅 어려움...

**Comment by hyenny** [comment]
## 변수의 스코프를 최소화하는 것이 좋다
- 프로퍼티보다 지역변수
- 최대한 좁은 스코프를 갖도록 변수 사용

### 스코프를 좁게 만드는 것이 좋은 이유
- 프로그램을 추적하고 관리하기 쉬움

### 변수는 정의할 때 초기화!
- 나중에 초기화할 수 있지만, 왠만하면 정의할 때 초기화하자
```
// 나쁜 예 (java를 사용했을 때 이런 식으로 많이 사용했는데..)
val user: User
if (hasValue) {
	user = getValue()
} else {
	user = User()
}

// 조금 더 좋은 예 
val user: User = if(hasValue) {
	getValue()
} else {
	User()
}
```
- 여러 프로퍼티를 한꺼번에 설정해야 하는 경우 구조분해 선언 활용
```
// 나쁜 예
fun updateWeather(degrees: Int) {
	val description: String
	val color: Int
	if (degrees < 5) {
		description = "cold"
		color = Color.BLUE
	} else if (degrees < 23) {
		description = "mild"
		color = Color.YELLOW
	} else {
		description = "hot"
		color = Color.RED
	}
}

// 조금 더 좋은 예
fun updateWeather(degrees: Int) {
	val (description, color) = when {
		degrees < 5 -> "cold" to Color.BLUE
		degrees < 23 -> "mild" to Color.YELLO
		else -> "hot" to Color.RED
	}
}
```
### 변수의 스코프가 넓으면 위험한 이유
- 캡처링

### 느낀점 & 생각
- 자바 사용하다가 코틀린 넘어오고 좋았던 점 중 하나가 구조분해였다. 같은 조건문에 초기화되는 여러 프로퍼티가 있을 때 깔끔하게 정리되서 좋았다. 
- 스코프를 최소화하란 건 당연하다고 생각했는데.. 캡처링 부분은 이해가 안됬다.

**Comment by pkch93** [comment]
**_최대한 좁은 스코프를 가지는 것이 좋다._**

Kotlin에서는 기본적으로 중괄호를 기반으로 스코프가 만들어 지며 내부 스코프에서는 외부 스코프에 있는 요소에만 접근할 수 있다. 참고로 람다와 같이 스코프 내부에 스코프가 존재할수도 있다. (21p)

변수의 스코프가 너무 넓으면 다른 동료 개발자에 의해 변수가 잘못 사용될 수 있다. 이런 경우가 너무 많아지면 프로젝트 코드를 이해하기 굉장히 어려워진다. (22p)

```kotlin
var selected: User

// ...

for (user in users) {
  if (user.age > 30) {
    selected = user
    println("선택된 유저의 이름은 ${user.name}입니다.")
  }
}
```
위와 같이 더 넓은 범위의 스코프에서 `selected`를 선언하는 경우 다른 스코프에서도 활용이 가능하다. 위 코드는 결국에는 for문 내에서 사용을 하기 위해 `selected`를 선언했는데 불필요하게 스코프를 넓게 잡은 꼴이 된다. 때문에 다른 개발자에 의해 다른 로직에서 `selected`가 오용될 수 있으며 `selected`의 실제 할당 지점을 찾아야하는 부분 때문에 프로그램의 복잡도도 증가한다.

이런 점에서 변수는 정의할 때 초기화 되는 것이 좋다. Kotlin에서는 if, when, try-catch, elvis 표현식으로 변수 초기화를 지원하므로 보다 편하게 초기화가 가능하다. (22p)

```
for (user in users) {
  val selected = if (user.age > 30) { user } else continue
  println("선택된 유저의 이름은 ${user.name}입니다.")
}
```
> 그리고 스코프와는 무관하게 val을 사용해서 다른 스코프에서 프로퍼티의 변경이 되지 않도록 불변 처리한다면 불변 객체의 이동만 파악하면 되므로 보다 복잡도를 낮출 수 있다.

**Comment by cmg1411** [comment]
- 프로퍼티보단 지역변수
- 지역변수는 최소 스코프로

구조분해선언은 변수의 스코프를 최소화 시킬 수 있는 방법이다.
여러 변수를 하나의 `식(expression)` 으로 한번에 초기화 할 수 있다.

캡처링 챕터에서 시퀀스를 이용한 코드는 이해가 잘 안가네요.. 같이 이야기해보면 좋을 것 같습니다ㅠ
