### ISSUE TITLE
Item 20. 일반적인 알고리즘을 반복해서 구현하지 말라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#20]
`Item 20. 일반적인 알고리즘을 반복해서 구현하지 말라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
이번 Item 20에서 말하는 “일반적인 알고리즘”은 특정 프로젝트에 국한된 것이 아닌 수학적인 연산, 수집 처리와 같이 별도의 모듈 또는 라이브러리로 분리할 수 있는 부분을 의미한다.

특히 컬렉션 내에 데이터를 정렬하는 로직은 표준 라이브러리에서 `sort`로 매우 잘 구현이 되어 있다. 표준 라이브러리의 로직은 모두 테스트가 되어 안정화된 상태로 배포가 되므로 믿고 사용할 수 있다.

> Kotlin의 표준 라이브러리는 `stdlib` 이다.
>
> 사실 `stdlib`에 매우 많은 함수들이 구현되어 있으므로 한번 살펴보는 것이 좋다.

상황에 따라 표준 라이브러리에 없는 로직이 필요할 수 있다. 이 경우 범용 유틸리티 함수 `universal utility function`로 정의하는 것이 좋다. 이는 여러번 사용하지 않더라도 범용 유틸리티 함수로 지정하는 것이 좋다.

동일한 결과를 얻는 함수를 여러 곳에 중복으로 정의하는 것은 유지보수 비용을 높이므로 함수는 중복되지 않게 기존에 관련된 함수가 있는지 확인하는 작업이 선행되어야한다.

**Comment by hyenny** [comment]
### 일반적인 알고리즘은 표준 라이브러리에 구현이 되어 있는지 확인
일반적인 알고리즘이 표준 라이브러리(stdlib)에 있을 경우 새로 만들지 말고 기존 라이브러리의 함수를 사용한다. 장점은 아래와 같다
- 코드 작성 속도가 빨라진다.
    - 호출 한 번 하는 것이 알고리즘을 만드는 것보다 빠르다.
- 구현을 따로 읽지 않아도 함수의 이름 등만 보고도 무엇을 하는지 확실하게 알 수 있다.
- 직접 구현할 때 발생할 수 있는 실수를 줄일 수 있다.
- 제작자들이 한 번만 최적화하면, 이러한 함수를 활용하는 모든 곳이 최적화의 혜택을 받을 수 있다.

### 표준 라이브러리에 없는 알고리즘이 필요할 경우?
범용 유틸리티 함수로 정의한다. 확장 함수로 구현하면 좋다.
```
fun Iterable<Int>.product() =
	fold(1) { acc, i -> acc * i }
```
여러 번 사용되지 않더라도 위와 같이 만드는 것이 좋다.

- 확장 함수의 장점
    - 함수는 상태를 유지하지 않으므로 행위를 나타내기 좋다. 특히 부가 작용(side-effect)이 없는 경우 더 좋다.
    - 톱레벨 함수와 비교해서, 확장 함수는 구체적인 타입이 있는 객체에만 사용을 제한할 수 있으므로 좋다.
    - 수정할 객체를 아규먼트로 전달받아 사용하는 것보다 확장 리시버로 사용하는 것이 가독성 측면에서 좋다.
    - 확장 함수는 객체에 정의한 함수보다 객체를 사용할 때 자동 완성 기능 등으로 제안이 이루어지므로 쉽게 찾을 수 있다.
        - ex. TextUtils.isEmpty(”Text”) 보다 “Text”.isEmpty()가 더 사용하기 쉽다.
       
### 생각
- 코틀린은 표준 라이브러리가 풍부하다는 게 장점이다. 프로젝트에서 처음 보는 확장 함수를 발견했을 때 조회해보면 90%가 표준 라이브러리에서 구현된 함수였다. 자바에서는 유틸리티 클래스를  만들고 일일이 테스트 케이스 만들면서 검증했는데 코틀린은 왠만한 알고리즘은 구현되어 있으니 가져다 사용만 하면 되서 너무 편했다. 
- 표준 라이브러리에 구현된 알고리즘이 없어도 확장함수로 만들면 IDE의 자동완성 혜택을 받을 수 있어 편리하다.

**Comment by aegis1920** [comment]
```
item.source.map(::sourceToEntry)

private fun sourceToEntry(source: Source) = SourceEntry()
.apply {
  id = source.id
  category = source.category
  country = source.country
  description = source.description
}
```

> 가급적 표준 라이브러리를 사용하고 없다면 확장 함수를 만들어서 사용하자

**Comment by cmg1411** [comment]
## 공통 알고리즘을 정의 하면 좋은 점
코드 작성이 빠르다.
이름을 한번 익혀 놓으면 다음에 읽기가 쉬워 진다.
실수를 줄일 수 있다.
한번의 최적화를 전역에 적용할 수 있다.

## 커스텀 유틸리티
- 범용 유틸리티 함수로 만들자.(최상위로)
	-  많이 쓰이지 않더라도. 누군가가 똑같은거 다시 만들지 않게.
-  확장함수로 만들자.
	- 톱레벨 함수. 프로퍼티 위임. 클래스 등으로도 만들 수 있겠지만, 확장함수로 만들자.
	- 클래스에 비해 : 상태를 가지지 않으므로 행위를 나타내기 좋다.
	- 톱레벨 함수에 비해 : 특정 타입을 지정할 수 있어서 좋다.
	- 톱레벨 함수에 비해 : 자동 완성의 기능을 사용할 수 있다. (isEmpty(“text”) 보단 “text”.isEmpty())
	- 인자를 받는 것 보다 확장 리시버가 더 가독성이 좋다.
