### ISSUE TITLE
Item 21. 일반적인 프로퍼티 패턴은 프로퍼티 위임으로 만들어라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#21]
`Item 21. 일반적인 프로퍼티 패턴은 프로퍼티 위임으로 만들어라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
Kotlin은 코드 재사용과 관련해서 프로퍼티 위임이라는 기능을 제공한다. 이를 통해 일반적인 프로퍼티 행위를 추출하여 재사용할 수 있다.

> Kotlin에서는 Delegates.obervable, Delegates.vetoable, Delegates.notNull, lazy와 같이 이미 구현되어있는 프로퍼티도 있다.

프로퍼티 위임은 간단하고 type-safe하게 구현할 수 있다. 이런 점에서 Java는 보통 어노테이션을 활용한 방법을 많이 사용하므로 차이를 보인다.

프로퍼티 위임을 구현하기 위해서는 getter와 setter를 정의해야한다. Kotlin에서는 getter와 setter를 위임하는 객체에게 넘기는 방식을 통해서 프로퍼티 위임을 구현한다. 이때 위임하기 위한 getter와 setter의 이름이 중요한데 각각 getValue와 setValue로 명명해야한다.

```kotlin
class LoggingProperty<T>(
	var value: T
) {
	operator fun getValue(
		thisRef: Any?,
		prop: KProperty<*>,
	): T {
		print("${prop.name} returned value $value")
		return value
	}

	operator fun setValue(
		thisRef: Any?,
		prop: KProperty<*>,
		newValue: T,
	) {
		print("${prop.name} changed from $value to $newValue")
		value = newValue
	}
}
```

위와같이 정의한 위임용 프로퍼티는 by를 통해 사용할 수 있다.

```kotlin
val post: Post("title", "content") by LoggingProperty<Post>
```

이때 위임 프로퍼티의 getValue와 setValue는 단순히 값만 처리하도록 변경하는 것이 아니라 컨텍스트 `this`와 프로퍼티 레퍼런스의 경계도 함께 사용하는 형태로 변경된다. 프로퍼티에 대한 레퍼런스는 이름, 어노테이션과 관련된 정보를 얻는데 사용되며 컨텍스트는 함수가 어떤 위치에서 사용되는지와 관련된 정보를 제공한다.

이런 정보로 인해서 getValue나 setValue가 여러개가 있어도 문제가 없다. 컨텍스트를 활용하므로 상황에 따라 적절한 getValue나 setValue가 사용된다.

# 여러 getValue와 setValue 정의가 가능한가?

하지만 Kotlin에서는 여러 getValue와 setValue는 컴파일 에러를 내뿜는다.

```kotlin
operator fun getValue(nothing: Nothing?, property: KProperty<*>): Any {
    TODO("Not yet implemented")
}
```

다음과 같이 첫번째 인자가 `Nothing?` 타입인 getValue 함수가 정의되어 있어야 비로소 컴파일 에러가 해결된다. 단, `Nothing?` 파라미터의 getValue로 프로퍼티 위임이 처리된다.

**Comment by aegis1920** [comment]
- 코틀린은 코드 재사용과 관련해서 프로퍼티 위임이라는 새로운 기능을 제공한다
    - lazy 프로퍼티(지연 프로퍼티)는 처음 사용하는 요청이 들어올 때 초기화되는 프로퍼티를 의미한다
    - `val value by lazy { createValue() }`
- 좋은 예로 뷰, 리소스 바인딩, 의존성 주입, 데이터 바인딩 등이 있다. 이런 패턴들을 자바에서 사용하기 위해서는 어노테이션을 많이 활용해야 하지만, 코틀린에서는 프로퍼티 위임을 통해 간단하고 type safe하게 구현할 수 있다

```
// 데이터 바인딩
private val port by bindConfiguration("port")
private val token String by preference.bind(TOKEN_KEY)
```

```kotlin
var token: String? by LoggingProperty(null)
var attempts: Int by LoggingProperty(0)

private class LoggingProperty<T>(var value: T) {
    operator fun getValue(
        thisRef: Any?,
        prop: KProperty<*>
    ): T {
        print("${prop.name} returned value $value")
        return value
    }

    operator fun setValue(
        thisRef: Any?,
        prop: KProperty<*>,
        newValue: T
    ): T {
        val name = prop.name
        print("$name changed from $value to $newValue")
        value = newValue
    }
}
```

> 프로퍼티 위임은 프로퍼티가 특정 행위를 할 때 내가 정의하는 함수를 실행시켜줄 수 있는 기능이다.
lazy는 해당 프로퍼티가 처음 사용될 때 실행된다.
Delegate.observale()은 해당 프로퍼티가 변경될 때마다 실행된다.
커스텀해서 get, set할 때 마다 특정 함수를 실행시켜줄 수도 있다.

**Comment by cmg1411** [comment]
## by 를 이용한 위임 패턴
1. by <getValue 또는 setValue 연산자 오버로딩한 클래스>
2. by lazy
3. by Delegates.observable
4. by Delegates.vetoable
5. by Delegates.notNull

## lateinit vs by lazy
| 구분 | lateinit                       | by lazy {}                                    |
|----|--------------------------------|-----------------------------------------------|
| 0  | var 만 가능                       | val 만 가능                                      |
| 1  | var 이기에 이후 값 변경 가능             | val 이기에 이후 값 변경 불가능                           |
| 2  | notnull 만 가능                   | nullable, notnull 둘 다 가능                      |
| 3  | primitive 불가능                  | primitive 가능                                  |
| 4  | custom getter/setter 없는 것 만 가능 | custom getter/setter 없는 것 만 가능                |
| 5  | 로컬 변수 불가능                      | 로컬 변수 가능, 클래스 생성자에선 불가능                       |
| 6  | 선언과 초기화가 떨어져 있음.            | 선언에서 어떻게 초기화 할건지 명시해야함.                       |
| 7  | 직접 backingField 를 가지는 구조       | Lazy 라는 객체로 랩핑된 프로퍼티를 가지는 구조. 직접 프로퍼티 접근 불가능. |
| 8  |                                | 동기화 기능 제공. 그에 따른 약간의 오버헤드                     |

> lateinit 에서 primitive type 을 사용할 수 없는 이유는
> lateinit 는 notnull 만 가능하고, 컴파일하면 만들어지는 get, set 에서 nullable 체크를 하는데, primitive type 은 nullable 이 존재하지 않으므로 설계상 컴파일 에러가 난다.

lateinit -> 절대로 Null이 될 수 없는 프로퍼티인데 초기화를 선언과 동시에 해줄 수 없거나 성능이나 기타 다른 조건들로 인해 최대한 초기화를 미뤄야 할 때
by lazy -> 초기화를 어떻게 할지 정해져 있고, 그렇기에 실수를 줄이기 위해 붙여 쓰면 좋을 때.

> by lazy 는 기본적으로 동기화(Thread-Safe) 를 제공한다.
> LazyThreadSafetyMode 타입 인자를 줄 수 있다. 이는 동기화 정도를 나타낸다.
> 동기화를 챙길 수 있는 대신, 약간의 오버헤드가 발생한다.
> 멀티스레드 환경에 따라서 적절한 동기화 레벨을 지정해서 오버헤드를 줄이도록 한다. 또는 lateinit 으로 바꾸거나.


## lateinit vs by Delegates.notNull()
| 구분         | lateinit                                           | by Delegates.notNull()                                |
|------------|----------------------------------------------------|-------------------------------------------------------|
| 0          | var 만 가능                                           | var 만 가능 (val 이 실제로 컴파일 에러는 안나나, 초기화를 못하므로 결국 런타임 에러) |
| 1          | notnull 만 가능                                       | notnull 만 가능 (null 초기화 하려 하면 에러)                      |
| 2          | primitive 불가능                                      | primitive 가능                                          |
| 3          | 선언과 초기화가 떨어져 있음.                                | 선언과 초기화가 떨어져 있음.                                      |
| 초기화 전에 사용시 | UninitializedPropertyAccessException | IllegalStateException                                 |

> 컴파일된 lateinit 는 처음에는 null 을 가진 필드로 관리되나, getter 와 setter 에서 null check 를 하고 있어서, 실제로는 null 을 가질 수 없다.

> by Delegates.notNull() 는 ReadWriteProperty 로 랩핑된 객체를 필드로 갖는다. 따라서 primitive type 을 사용할 수 있다.
> 그리고 랩핑으로 인한 약간의 오버헤드가 있다.


## 프로퍼티 위임 패턴
프로퍼티에 붙은 by 오른쪽의 getValue() / setValue() 에 동작을 위임한다고 생각하면 된다.
따라서, 프로퍼티가 val 이라면 getValue(), var 이라면 getValue(), setValue() 를 구현해야한다.
정해진 형태의 getValue(), setValue() 를 구현한 어느 클래스든 by 를 통해 위임할 수 있지만,
ReadWriteProperty, ReadOnlyProperty 인터페이스를 사용하면 더 편히 구현할 수 있다.
