### ISSUE TITLE
Item 26. 함수 내부의 추상화 레벨을 통일하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#26]
`Item 26. 함수 내부의 추상화 레벨을 통일하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
계층화의 장점은 명확하다. 어떤 계층에서 작업할 때 그 아래 계층은 이미 완성되어있으므로 해당 계층만 생각하면 된다. 즉, 전체를 이해할 필요없이 해당 계층만 생각하면 된다는 것이다.

# 추상화 레벨?

종종 추상화 레벨이 높다/낮다 라고 표현한다. 위 캡처에서 추상화 레벨이 높다는 것은 물리 장치로부터 멀어진다는 의미이다. 프로그래밍에서는 프로세서로부터 멀어진다고 표현한다. 때문에 추상화 레벨이 높을수록 단순함을 얻는다. 하위 게층에서 제공하는 기능을 사용하면 프로세서 단도 그에 맞게 동작하기 때문이다. 단, 프로세서를 세부적으로 제어할수는 없다.

# 추상화 레벨 통일하기

위 캡처와 같이 컴퓨터 과학을 추상화 계층으로 나눈 것처럼 애플리케이션 코드도 계층을 나눠서 사용할 수 있다. 이를 위한 가장 기본적인 도구가 바로 함수이다. 함수를 통해서 추상화 레벨을 높게 또는 낮게 구분할 수 있으며 이에 대한 원칙도 추상화 레벨 원칙 `Single Level of Abstraction, SLA`라는 말로 존재한다.

추상화 레벨 원칙을 지킨 코드는 함수가 최소한의 책임만 가진다. “함수는 작아야 하며, 최소한의 책임만을 가져야 한다.” 라는 규칙을 지키기 때문이다. 이렇게 작은 단위로 나눠지면 재사용과 테스트가 쉬워진다.

# 소프트웨어 아키텍처의 추상 레벨

함수 뿐만 아니라 프로그램 아키텍처에도 추상화 레벨을 적용할 수 있다. 이렇게 추상화를 구분하는 이유는 서브 시스템의 세부 사항을 숨김으로 상호 운영성과 플랫폼 독립성을 얻기 위함이다.

계층이 잘 분리된 프로젝트를 계층화가 잘 된 프로젝트라고 부르며 이는 좋은 프로젝트의 기준이 된다. 계층화가 잘 된 프로젝트는 어떤 계층 위치에서 코드를 봐도 일관적인 관점을 얻을 수 있다.

# Item 26을 학습하면 든 생각

Java에서는 모듈별로 의존성을 나누는 것에 대한 지원이 약하다고 생각한다. package-level 접근 제어자는 패키지 단위로 동작하지 모듈단위로 동자하지 않는다. 때문에 이를 잘 사용하기 위해서는 패키지에 클래스가 매우 비대해지고 오히려 프로젝트의 복잡도를 높이지 않나 생각이 든다. 때문에 Java 진영의 대표적인 빌드 도구인 Maven과 Gradle에서는 멀티 모듈 기능을 제공하고 있으며 Java 9부터는 package-info.java를 활용한 모듈화도 진행한다.

> 단, Java 9 모듈화를 사용한 Java 개발자를 단 한명도 본적이 없다..

Kotlin에서도 internal 접근 제한자로 모듈 단위의 접근성을 제공한다. package-level을 없애고 internal을 지원하는 이유는 결국 앞서 말한 package-level의 한계 때문이 아닐까 싶다.

Kotlin에서는 빌드 도구의 멀티 모듈 기능과 internal 접근 제한자를 잘 활용하면 수준 높은 추상화 단계를 구성할 수 있지 않을까 생각한다.

**Comment by rockjoon** [comment]
## item26. 함수 내부의 추상화 레벨을 통일하라.

### 추상화를 하는 이유
* 복잡성을 숨기기 위해
* 코드를 체계화 하기 위해
* 만드는 사람에게 코드 변화의 자유를 주기 위해

### 추상화 레벨 통일
* (함수의 경우) 하나의 함수에서 많은 일을 한다면 이를 여러개의 최소한의 책임을 갖는 낮은 레벨의 함수로 분리

### 프로그램 아키텍처의 추상레벨
* 서브시스템의 세부 사항을 숨기고, 상호 운영성과 플랫폿 독립성을 얻을 수 있다.
* 예를 들어 입출력을 나타내는 모듈은 낮은 레벨의 모듈이 되고 비즈니스 로직을 나타내는 부분이 높은 레벨의 모듈이 된다.

> 추상화 레벨 "통일"이라는 표현에서 하나의 프로젝트에서 같은 추상화 레벨만을 사용하라는 의미인가? 생각했었다.
> 하지만 결국 추상화 레벨을 "구분"하여 사용하라는 의미이다.

**Comment by cmg1411** [comment]
추상화 레벨을 맞춰라.

1.코드의 추상화 레벨 함수는 작아야하며 최소한의 책임만 가져야한다. 를 맞춘다. 메서드가 작아지면 추상화 레벨을 맞출 수 있다.

2.아키텍쳐 추상화 레벨
```
  4.높은 레벨 문제 중심
  3.낮은 레벨 문제 중심
  2.낮은 레벨 구현 구조
  1.프로그래밍 언어 구조와 도구
  0.운영체제 연산과 머신 명령
```
또는 클린 아키텍쳐, 멀티모듈 같은 것도 추상화 레벨을 맞춘 것.

3.프로젝트 레벨 쉽게 말해 Git Repository 단위 추상화. 기준이 뭘까.. 서로의 의존성이 얼마나 있어야 같은 레벨인가. 또는 한명의 개발자가 같이 알아야 하는 것이 하나의 추상화 레벨인가?
