### ISSUE TITLE
Item 27. 변화로부터 코드를 보호하려면 추상화를 사용하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#27]
`Item 27. 변화로부터 코드를 보호하려면 추상화를 사용하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
추상화로 실질적인 코드를 숨기면 사용자가 세부 사항을 알지 못해도 괜찮다는 장점이 있다. 여기서 “추상화”의 의미는 클래스 상속/인터페이스 구현 뿐만 아니라 상수 추출, 함수 분리 등까지 포함한다.

# 상수

상수는 가장 간단한 추상화 방법이다. 상수를 사용하여 의미를 부여하면 한눈에 알아볼 수 있으며 함수 내부의 로직을 전혀 이해하지 못해도 위 상수만 변경하면 된다. 때문에 2번 이상 사용되는 값은 상수 추출이 좋다.

> 1번만 사용될 것으로 예상되는 값은 굳이 상수로 뺄 필요는 없다고 생각한다. 오히려 가독성을 해친다고 생각한다. 대표적으로 에러메세지가 있을 것이다.

# 함수

일반적인 알고리즘을 함수로 추출하여 여러 곳에서 사용될 수 있는 로직의 중복을 방지하고 프로그래밍에 편의성을 줄 수 있다.

# 클래스와 인터페이스

함수의 단점은 상태를 유지하지 못한다는 것이다. 그리고 함수 시그니처를 변경하면 프로그램 전체에 영향을 줄 수 있다. 구현을 추상화하는 더 강력한 방법으로 클래스가 있다. 클래스가 함수보다 더 강력한 이유는 **상태를 가질 수 있으며 메서드를 가질 수 있다는 것**이다.

인터페이스는 클래스를 더 추상적이게 만들 수 있는 방법이다. 인터페이스를 활용하면 클래스를 직접 사용하지 못하므로 인터페이스만 유지하는 방식으로 유지보수성을 높일 수 있다. 즉, 인터페이스 뒤에 실제 객체를 숨겨 실질적인 구현을 추상화하고 사용자는 추상화된 것에만 의존하도록 만드는 것이다. 이를 통해 결합도를 줄일 수 있다.

# 추상화의 장단점

지금까지 알아본 추상화의 방식은 다음과 같다.

- 상수 추출
- 동작을 함수로 정의
- 클래스로 정의
- 인터페이스로 클래스를 추상화
- 보편적인 객체를 특수한 객체로 래핑

이를 통해 자유도를 높여주고 유지보수성을 높일 수 있다.

단, 추상화에는 장점만 있는 것은 아니다. 추상화 수준이 너무 높아지면 오히려 코드 파악이 힘들어질 수 있다. 여러 인터페이스, 클래스를 타고 봐야하기 때문이다. 때문에 프로젝트가 적절한 추상화를 이룰 수 있도록 균형을 유지해야하는 것이 중요하다.

**Comment by rockjoon** [comment]
## item27. 변화로부터 코드를 보호하려면 추상화를 사용하라

## 함수, 클래스, 인터페이스
* 함수보다 클래스가, 클래스보다 인터페이스가 더 추상화 레벨이 높다.
* 추상화 레벨이 높을 수록 자유도가 높아진다.

## id 만들기
* id 생성 방식이 변경될 것을 대비하여 함수를 사용
* id 타입이 변경될 것을 대비하여 id를 클래스화 할 수 있다.

## 추상화의 문제
* 추상화는 변화의 "자유"를 주지만, 수정을 어렵게 한다.
* 추상화된 코드를 읽고 수정하려면 해당 개념을 잘 이해해야 한다.

> 추상화의 균형을 맞추는 방법은 책에서도 결국 진리의 케바케를 사용하는 군요...

**Comment by cmg1411** [comment]
# 특정 로직을 함수로 추상화 하면, 함수를 사용하는 부분에 영향을 주지 않고 함수를 수정할 수 있다.

1. 상수
- 반복적으로 사용되는 리터럴을 상수로 만들자.
- 쉽게 변경 가능. 의미를 가지게 됨.

2. 함수
2-1. 로직을 함수(또는 확장함수)로 추상화
2-2. 함수 자체를 높은 레벨의 함수로 추상화
    - 로직을 함수로 추상화 했다면, 여러가지 추상화된 함수를 선택하는 더 높은 레벨의 추상화 메서드를 만들 수 있다.
    - 디자인 패턴들 알면 좋을 듯.

3. 클래스
- 함수에 비해 `상태`를 가질 수 있다.
- 하지만 클래스는 모든걸 숨기지 못한다. 프로퍼티, 메서드 등을 더 숨기려면 인터페이스를 사용하자.

4. 인터페이스
- listOf 의 반환 타입 List, 컬렉션 처리 확장함수들의 반환값인 Map, List, Set ... 모두 인터페이스.
- 프로퍼티 위임도 ReadOnlyProperty, ReadWriteProperty 등 인터페이스를 사용.
- 내부 클래스의 가시성을 제한하고, 인터페이스를 통해서 노출시킬것만 노출.
- 인터페이스만 유지한다면, 구현체를 마음대로 바꿀 수 있다.
- 테스트에서도 인터페이스 faking이 클래스 mocking보다 간단하기 때문에 별도의 mocking 라이브러리를 사용하지 않아도됨.
    - `val interFace: InterFace = TestImplement()`

5. 일반적인 객체를 랩핑한 특수 객체
- value class 같은걸 말하는 것 같다.
- 단순한 하나의 값을 클래스로 랩핑하면 추상화가 되어 내부 변경이 수월하다.



# 균형 있는 추상화
추상화를 너무 많이하면 코드가 과하게 복잡해진다.
- 팀의 크기
- 팀의 경험
- 프로젝트의 크기
- 특징
- 도메인 지식
에 따라 다음과 같은 규칙으로 추상화 하는게 좋다.
1. 많은 개발자가 참여하면, 이후에 객체 생성과 사용 방법을 수정하기 어렵다. 최대한 모듈과 부분을 분리한 추상화를 하는게 좋다.
2. 테스트를 하거나, 애플리케이션을 기반으로 다른 새로운 애플리케이션을 만든다면 추상화 하는게 좋다.
3. 프로젝트가 작고 실험적이라면, 추상화하지 않고 직접 변경해도 괜찮다. 오류가 발생하면 빨리 변경하면 된다.

`추상화는 단순히 코드의 중복을 제거하기 위함이 아니라, 변화에 유연하게 하기 위해 사용한다.`
