### ISSUE TITLE
Item 28. API 안정성을 확인하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#28]
`Item 28. API 안정성을 확인하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
대부분의 경우 안정적이고 표준적인 API를 선호한다.

- API가 변경되는 경우 이를 사용하는 로직에서 변경이 필요할 수 있다. 때문에 버전이 올라가더라도 하위 호환성을 제공해주는 라이브러리를 선호하는 경향이 있다.
- 새로운 API를 배우는 것은 학습 비용이 드므로 널리 사용할 수 있는 안정적인 모듈/라이브러리를 학습하는 것을 선호한다.

# 시멘틱 버저닝

라이브러리와 모듈의 안정성을 나타내는 방법으로 보통 버전을 사용한다. 이때 가장 널리 사용되는 버저닝 방법이 시멘틱 버저닝 `Semantic Versioning, SemVer`이 있다.

시멘틱 버저닝은 MAJOR, MINOR, PATCH/BUGFIX로 온점 `.`으로 나누어서 구성한다. 즉, `{MAJOR}.{MINOR}.{PATCH/BUGFIX}`로 버전을 구성한다.

- MAJOR
    
    호환되지 않은 수준의 API 변경. 이전 버전에서 제공하던 API가 삭제될 수 있다. 이때 MAJOR 버전이 0인 경우 안정적이지 않다는 의미이므로 주의해야한다.
    
- MINOR
    
    이전 변경의 호환성을 유지하면서 기능을 추가하는 방식
    
- PATCH
    
    기능의 변경 없이 버그 수정 또는 보안 안정성 개선
    

보통의 모듈/라이브러리는 시멘틱 버저닝 방식을 사용하므로 버전 확인을 하면서 업데이트가 필요하다.

# 라이브러리 사용자가 많을수록 안정적이다.

일반적으로 모듈/라이브러리의 안정성을 알아보는 가장 쉬운 방법은 사용자 수를 확인하는 것이다. github star의 수도 좋은 지표가 될 수 있다. 모듈/라이브러리 사용자가 많을수록 API 작성자도 변경에 신중을 기할 수 밖에 없다.

**Comment by rockjoon** [comment]
## item28. api안정성을 확인하라
* 가능한한 안정적인 api를 사용
* api의 버전 이름, 문서, 어노테이션 등을 통해 더욱 안전한 설계가 가능해짐

**Comment by cmg1411** [comment]
# 안정적이고 표준적인 API
- 문제가 없어서 변하지 않는 API.

# 안정적인 API 가 좋은 이유
- API 가 바뀌었을 때 수정해야 할 곳이 너무 많다. 바뀌어야 하는 곳이 너무 많아서 라이브러리 업데이트를 꺼려하는 상황은 매우 좋지 않다.
- 새로운걸 학습해야한다.

# 하지만.
- 바로 안정적인 API 를 만들기란 쉽지 않다. 계속해서 개발해나가기 마련.

# 시멘틱 버저닝.
- Major, Minor, Patch 로 나눈 1.1.1 과 같은 버저닝.
- Major : 하위 호환성이 없는 변경사항
- Minor : 하위 호환성이 있는 변경사항
- Patch : 하위 호환성이 있는 버그 수정

과거 라이브러리를 유지해줘서, 라이브러리 업데이트 접근성을 높인다.
또한, 버전마다의 API 의 불안정을 명확하게 알려준다.


# Experimental
변경될 가능성이 높은 요소는 Experimental 을 붙인다.
```kotlin
@Experimental(level = Experimental.Level.WARNING)
@ExperimentalPathApi
@ExperimentalUnsignedTypes
```

# Deprecate
안정적인 API 를 변경해야한다면, @Deprecate 를 통해 알려서, 변경할 수 있는 시간을 준다.
