### ISSUE TITLE
Item 29. 외부 API를 래핑하여 사용하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#29]
`Item 29. 외부 API를 래핑하여 사용하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
API 설계자가 안전하지 않다고 하거나 안전하다고 하더라도 신뢰할 수 없다면 해당 API는 불안정하다고 할 수 있다. 만약 불안정함에도 이런 API를 사용해야한다면 래핑 `Wrapping`해서 사용하는 것도 방법이다.

래핑을 하면 다음과 같은 장점을 얻을 수 있다.

- 문제가 있다면 래퍼 함수/클래스만 변경하면 되므로 API 변경에 쉽게 대응할 수 있다.
- 프로젝트의 스타일에 맞춰서 API의 형태를 조정할 수 있다.
- 특정 라이브러리에서 문제가 발생하면, 래퍼를 수정하여 다른 라이브러리를 사용하도록 변경할 수 있다.
- 쉽게 동작을 추가/수정할 수 있다.

**Comment by rockjoon** [comment]
## item29. 외부 API를 랩해서 사용하라.
* 불안전하다고 판단되는 api는 래퍼를 통해 사용한다.
* api가 변경되더라도 래퍼만 변경하면 되지만, 래퍼에 대한 비용이 따른다.

**Comment by cmg1411** [comment]
# 외부 API 를 랩핑해서 사용
- 외부 API 를 신뢰하기 어렵지만 사용해야한다면, Wrapping 하라.
- 만약 문제가 생겼을 때 변경할 수 있도록.

## 장점
1. 문제가 있다면 랩퍼만 변경하면 되므로 API 변경에 쉽게 대응 가능.
2. 프로젝트 스타일에 맞춰 API 형태를 조정 가능.
3. 라이브러리 자체의 변경도 용이.
4. 동작의 추가도 용이.

## 단점.
1. 랩퍼를 만들어야 한다.
2. 알아야할게 많다.
