### ISSUE TITLE
Item 3. 최대한 플랫폼 타입을 사용하지 말라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#3]
`Item 3. 최대한 플랫폼 타입을 사용하지 말라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by aegis1920** [comment]
### null 여부를 쉽게 체크할 수 있도록 노력하자

- null 여부를 알 수 없는 플랫폼 타입은 쓰지 말자
  - 만약 쓰게 됐다면 null 체크를 하자.
- 어쩔 수 없이 플랫폼 타입을 써야한다면 사진과 같이 as를 사용해서 nullable하게라도 만들자
- **java 코드 작성 시 `@NotNull`과 `@Nullable` 다는 것을 생활화하자**

<img width="691" alt="image" src="https://github.com/Meet-Coder-Study/effective-kotlin-study/assets/22311557/a372dca0-ced5-4233-9e41-5bcf229600f0">

**Comment by hyenny** [comment]
## 최대한 플랫폼 타입을 사용하지 않을 수..있나?
### 플랫폼 타입?
- 다른 프로그래밍 언어에서 전달되어 nullable인지 아닌지 알 수 없는 타입
- 타입 이름 뒤에 !기호를 붙여서 표기한다.
- ex. `String!`

### 플랫폼 타입 주의할 점
- 플랫폼 타입을 다룰 때는 null이 아니라고 생각되는 것이 null일 가능성이 있다. 
- 설계자가 명시적으로 어노테이션을 표시하거나, 주석으로 달아두지 않았다면 언제든지 동작이 변경될 가능성이 있다.
- 지금 당장 null을 리턴하지 않더라도, 미래에는 변경될 수 있다는 걸 염두해 두어야 한다.

### 자바와 코틀린을 함께 사용할 때
- 자바 코드를 직접 조작할 수 있다면 가능한 @Nullable과 @NotNull 어노테이션을 붙여서 사용을 권장한다. (코틀린 개발자를 지원하고 싶을 경우)

### 느낀점 & 생각
- 코틀린 프로젝트에서 자바 라이브러리를 쓸 때 이 때 플랫폼 타입을 많이 만나게 된다. 반환 타입이 not null 같음에도 @NotNull 안 붙여주는 경우가 대부분이라..그냥 nullable로 처리 중이다.  진짜 아닌 거 같을 땐 !! 쓰는데 이거 쓸 때마다 못생겨서 쓰기 싫음 vs ?. (safe call) 쓰기 싫음 둘 중 고민하게 된다. 여기서 알려준대로 모든 자바 개발자가 어노테이션으로 명시해주면 세상이 평화로울텐데, 탄식하며 아이템을 읽었다.
- 자바 -> 코틀린 전환할 경우 사전작업으로 어노테이션 다는 작업을 진짜 할까 궁금해졌다.

**Comment by pkch93** [comment]
**_플랫폼 타입은 nullable이 될 수 있다_**
- 플랫폼 타입이란 자바 등 다른 프로그래밍 언어에서 넘어온 타입을 의미한다. 특히 코틀린은 JVM 언어이므로 자바로 쓰여진 방대한 라이브러리를 사용할 일이 많다.
- 이때 타 언어 (특히 자바)에서는 모든 타입에서 null로 정의가 가능하기 때문에 nullable로 가정해야한다.
- 따라서 코틀린과 호환되는 자바 코드를 작성하는 경우 `@Nullable`이나 `@NotNull` 어노테이션을 사용해야 코틀린 내에서 타입을 확실히 하여 처리가 가능하다.

**_!는 플랫폼 타입을 나타낸다._**

플랫폼 타입은 타입 뒤에 !를 붙여서 표시된다. 참고로 프로그래머가 !를 붙여 표시할 수는 없다. 코틀린 컴파일러에 의해서 이를 표기해서 사용한다.

```java
public class Person {
	private String name;

	// ...

	public static Person getInstance() {
		return new Person();
	}
}
```
위와 같이 자바에서 작성된 Person이 있다고 가정한다. 이를 코틀린에서 사용하면 코틀린 컴파일러는 Person!로 추론한다.

```kotlin
fun main() {
	val p = Person.getInstance()
}
```
<img width="300" alt="스크린샷 2023-03-05 오후 2 06 50" src="https://github.com/Meet-Coder-Study/effective-kotlin-study/assets/30178507/ebbfcaac-f7b4-4663-8398-6e664a491b0a">

위와 같이 p는 Person!로 추론된다.

**_플랫폼 타입은 코틀린에서 사용하지 말자_**

```java
public class Person {
	public String getName() {
		return null;
	}
}
```

위와 같이 자바 클래스 `Person`의 `getName`이 null을 반환한다고 가정한다. 이를 코틀린에서 사용해본다.

```kotlin
fun statedType() {
	val name: String = Person().name // NullPointerException
}

fun platformType() {
	val name = Person().name
	println(name.length) // NullPointerException
}
```

전자인 `statedType`은 name을 가져오는 시점에서 NullPointerException이 발생한다. 이는 `String`으로 지정한 코틀린 타입은 null을 허용하지 않기 때문이다.

반면 `platformType`에서는 name을 받아오는 것까지는 가능하다. `Person!`로 추론되기 때문이다. 다만, name은 실제 null이기 때문에 length를 받아오는 시점에서 NullPointerException이 발생한다.

이처럼 플랫폼 타입이 null인지 아닌지 컴파일러가 확실히 처리할 수 없기 때문에 NPE의 가능성은 언제나 열려있게 된다. 비록 지금은 안전하게 쓰고 있더라도 null이 될 수 있는 가능성도 존재한다. 이를 해소하는 비용과 플랫폼 타입으로 인한 오류가 발생했을때 이를 찾는 비용이 만만치 않을 것이다.

이런 플랫폼 타입이 전파되는 것은 위 문제를 더 퍼트리게 된다. 때문에 플랫폼 타입은 되도록이면 사용하지 않는 것이 좋다.

**Comment by cmg1411** [comment]
### 플랫폼 타입

코틀린은 자바와 다르게 타입에 nullable | not null 이 명시 가능하다.
자바와 코틀린 코드를 같이 쓸 때, 자바 코드에 @NotNull 또는 @Nullable 에 맞게 코틀린에서 사용하면 된다.
하지만 이런 에너테이션이 없다면, 자바의 nullable 한 객체들을 코틀린에서 쓸 때 !! (assertion) 또는 널체크를 해줘야 하는데, 이게 불편하면 그대로 플랫폼 타입으로 사용하면 된다.

- ! (느낌표 하나) 가 끝에 붙는 타입
- null 인지 not null 인지 알 수 없음을 의미

### 플랫폼 타입을 되도록 사용하지 말자

```
// NotNull 타입
val value: String = JavaClass().value // 여기서 NPE
println(value.length)

// 플랫폼 타입
val value = JavaClass().value
println(value.length) // 여기서 NPE
```
플랫폼 타입은 자바 변수와 같게 사용하는 곳에서 NPE 가 터진다.
예외상황은 최대한 빠르게, 문제가 된 위치에서 확인하는 것이 좋다.

이는 자바에 없는 코틀린의 장점을 사용하지 않는 것이므로 플랫폼 타입은 사용하지 않는게 좋아 보인다.


### 플랫폼 타입 사용 주의점

위 코드에서
```
val value = JavaClass().value
```
부분은 타입 추론에 의해 플랫폼 타입이 된다.
만약 `JavaClass().value` 의 null 여부를 확실히 알고 있다면, 타입을 명시해주는것이 좋다.
