### ISSUE TITLE
Item 30. 요소의 가시성을 최소화하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#30]
`Item 30. 요소의 가시성을 최소화하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
보통 이미 공개된 API를 변경하는 것보다 새롭게 API를 작성해서 기능을 추가하는 것이 쉽다. 이미 공개된 API를 변경하는 것은 이를 사용하는 로직에 대한 확인이 필요하기 때문이다. 만약 라이브러리라면 더더욱 변경이 어려울 수 있다.

때문에 공개 API는 최소한으로 노출하는 것이 좋다. 코틀린에서는 Java와 마찬가지로 여러 가시성 한정자를 제공한다.

# 지원하는 가시성 한정자

클래스에서는 다음과 같은 4개의 가시성 한정자를 사용할 수 있다.

- public `default`
    
    가시성 한정자를 명시하지 않으면 기본적으로 공개 API로 만든다.
    
- private
    
    클래스 내부에서만 사용 가능하다.
    
- protected
    
    해당 클래스와 하위 클래스에서만 사용가능하다. 해당 클래스와 하위 클래스, 해당 패키지에서 사용가능한 Java와는 다르다.
    
- internal
    
    Java에는 없는 새로운 가시성 한정자이다. 모듈 단위에서만 접근 가능하다.
    

톱레벨 `Top-level` 요소에는 다음 세 가지 가시성 한정자를 사용할 수 있다.

- public `default`
- private
- internal

> 여기서 Java에는 package-level 가시성 한정자가 있었지만 코틀린에서는 지원하지 않는다. 대신 모듈 단위의 internal 가시성 한정자를 제공한다.

## 코틀린의 모듈 단위

여기서 `internal` modifier는 module 단위로 동작함을 알 수 있었다. Kotlin에서 module은 함께 컴파일 되는 Kotlin 파일들을 뜻한다.

- 인텔리J 모듈
- Maven Project
- gradle source set
- kotlinc ant task가 컴파일하는 파일들

**Comment by rockjoon** [comment]
## item30. 요소의 가시성을 최소화하라.
* 노출되는 인터페이스는 작을 수록 유지하기 좋다.
* 클래스나 요소는 한정자 등으로 노출을 제한시킨다.
* 상태를 외부에서 변경가능하지 않도록 설계한다.

**Comment by cmg1411** [comment]
# 인터페이스
1. 기존의 것을 숨기는 것 보다 새로운 것을 노출 시키는게 더 쉽다.
- 기존의 것을 숨길 때에는 대체제를 제공해야 하는데, 대체제를 만드려면 도메인 지식 다 알아야한다.
- 따라서 처음에는 최소한으로 노출하는 API 로 시작하는게 좋다.


# 클래스의 프로퍼티
- 프로퍼티의 수정이 필요하다면 `private set + public 수정 메서드` 를 만드는 것이 좋다.
- 또는 상태가 바뀔 때 마다 새로운 객체를 생성하던지.
- 가시성이 제한되면 클래스의 변경을 쉽게 추적할 수 있고, 동시성과 불변성을 지키기 용이하다.

# DTO
- dto 는 가시성을 제한하지 않는게 좋다.

# 상속의 한계
- 오버라이딩 한 것은 부모의 가시성을 무조건 따라야 한다.
- 컴포지션을 사용하는 대표적인 이유.
