### ISSUE TITLE
Item 31. 문서로 규약을 정의하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#31]
`Item 31. 문서로 규약을 정의하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
함수가 무엇을 하는지 명확하게 설명하고 싶다면 KDoc 주석을 붙여 주는 것이 좋다. 주석은 함수명이나 프로퍼티의 이름으로 부족한 설명을 보충하여 명확하게 설명할 때 추가하는 것이 좋다. 행위를 문서화하지 않는 경우면서 요소의 이름이 명확하지 않다면 사용자는 추상화 목표가 아닌 현재 구현에 의존하게 되므로 문서로 예상되는 행위를 설명하는 것도 좋은 방법이다.

# 규약?

규약이란 일종의 약속으로 해당 API를 의도대로 사용하기 위해 API 설계자의 의도이다. 규약이 적절하게 정의되어 있다면 클래스를 만든 사람은 클래스가 어떻게 사용될 지 걱정하지 않아도 된다. 때문에 규약만 잘 지킨다면 원하는 부분을 마음대로 수정할 수 있다.

반대로 규약을 설정하지 않는다면 클래스를 사용하는 사람은 할 수 있는 것과 없는 것을 구분할 수 없기 때문에 구현의 세부 정보에 의존하게 되므로 사용자의 구현을 망칠 우려가 있다. 따라서 규약을 설정하는 것은 중요하다.

## 규약 정의

규약을 정의하는 방법에는 여러가지가 있다. 이 중에서 이름, 주석과 문서, 타입이 대표적인 방법이다.

- 이름
    
    일반적인 개념과 관련된 메서드는 이름만으로도 동작을 예측할 수 있다. `ex. sum`
    
- 주석과 문서
    
    필요한 규약을 자유롭게 표현할 수 있는 방법이다.
    
- 타입
    
    타입은 객체에 대한 많은 것을 알려준다. 함수 선언에 있는 리턴 타입과 인자의 타입은 큰 의미가 있다.
    

# 주석

자바 커뮤니티 초기에는 “문학적 프로그래밍”이 인기였다. 문학적 프로그래밍은 주석으로 모든 것을 설명하는 프로그래밍 기법이다. 단, 현재에 들어서는 모든 것을 주석으로 설명하는 방식은 거의 볼 수 없다. 현재는 주석 없이도 읽을 수 있는 코드를 작성하는 프로그래밍 방식이 선호되기 때문이다.

주석은 규약을 더 명확하게 설명할 수 있는 좋은 도구이지만 남용하면 오히려 코드를 산만하게 만든다. 또한 주석은 컴파일러의 도움을 받을 수 없으므로 코드가 수정되었을때 함께 주석도 수정되지 않는다면 잘못된 정보를 알리는 주석이 될 수 있다.

때문에 함수의 이름과 파라미터만으로 명확히 표현할 수 있는 요소에는 주석을 달지 않는 것이 좋다. 좀 더 명확하게 설명이 필요한 요소에만 주석을 달자

# 타입 시스템과 예측

타입 계층은 객체와 관련된 중요한 정보이다. 여기서 상위 타입에서 어떤 동작을 할 것이라 예측되면 하위 타입에서도 이를 지원해야한다. 이를 **리스코프 치환 원칙**이라고 한다. 때문에 클래스가 어떤 동작을 할 것이라는 예측 자체가 잘못된다면 클래스와 관련된 다양한 상속 문제가 발생할 수 있다.

사용자가 클래스의 동작을 확실하게 예측할 수 있게 하려면 공개 함수에 대한 규약을 잘 지정해야한다. 특히 인터페이스 함수에 대한 규약을 잘 지정해야한다. 규약을 잘 지정하면 인터페이스를 더욱 유용하게 만들며 규약이 지켜지는 범위 내에서는 클래스를 자유롭게 구현할 수 있다.

# 조금씩 달라지는 세부 사항

구현 세부 사항은 항상 달라질 수 있다. 때문에 이런 세부 사항들을 최대한 공개하지 말고 보호하는 것이 좋다. 일반적으로 **캡슐화**를 통해서 이를 보호한다. 캡슐화가 많이 적용될수록 사용자는 구현 세부에 신경쓸 필요가 없어지므로 더 많은 자유를 가질 수 있다.

**Comment by rockjoon** [comment]
## item31. 문서로 규약을 정의하라.
> 한때 주석이 쿨하지 못하다고 생각했었다. 주석을 다는 것은 코드로 설명하지 못하는 실력의 부족이지 않을까 라는 생각도 했었다.   
그러나 개발을 하다 보니 주석은 생각보다 많은 것을 표현할 수 있다는 것을 느끼게 되었다. 당장 우리가 api들을 살펴보면서 가장 도움을  
받는 것도 주석이다. 주석을 쓰지 않아도 되면 가장 좋지만 *적절하게 작성된* 주석은 상당히 유용하다고 생각한다.
