### ISSUE TITLE
Item 32. 추상화 규약을 지켜라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#32]
`Item 32. 추상화 규약을 지켜라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
클래스를 상속하거나 인터페이스를 구현할 때는 클래스나 인터페이스에 정의된 규약을 반드시 지켜야한다. 이 규약을 지키지 않는다면 제대로 동작하지 않을 수 있다.

예를 들어 Any에 정의된 hashcode의 규약을 지키지 않는다면 HashMap, HashSet과 같은 클래스를 사용할 때 제대로 동작하지 않는다.

따라서 클래스와 인터페이스를 상속/구현할 때는 반드시 해당 클래스와 인터페이스가 정의한 규약대로 구현해야한다.

**Comment by rockjoon** [comment]
## item32. 추상화 규약을 지켜라.
* 안정적인 프로그램을 위해 규약을 지켜야 한다.

**Comment by cmg1411** [comment]
# 규약을 지키지 않는 예시
1. private 함수를 리플렉션으로 억지로 사용하는 경우
2. 코틀린 최상위 클래스인 Any 의 equals, hashCode 를 오버라이드 하지 않는 경우
   - 규약을 지킨다는 전제로 만들어진 HashMap(hashCode) 또는 Set(equals 로 중복제거) 가 제대로 동작하지 않는다.

# 규약을 깨야하는 경우
이유를 포함한 문서화를 꼭 하라.
