### ISSUE TITLE
Item 33. 생성자 대신 팩토리 함수를 사용하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#33]
`Item 33. 생성자 대신 팩토리 함수를 사용하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
클래스의 인스턴스를 생성하는 가장 기본적인 방법은 생성자를 사용하는 것이다. 그리고 생성자를 활용해서 다양한 디자인 패턴을 적용하여 객체 인스턴스를 생성할 수도 있다.

Java에서는 정적 팩토리 메서드, 팩토리 패턴 등을 사용하여 객체를 생성하는 다양한 방법을 사용했다. Kotlin에서도 비슷한 방법을 사용할 수 있지만 static 메서드를 선언할 수 없는 등 Java와의 차이 때문에 조금은 상이한 팩토리 함수 선언 방식을 가진다.

# Kotlin에서 적용할 수 있는 팩토리 함수

Kotlin에서는 Companion 객체 팩토리 함수, 확장 팩토리 함수, 톱레벨 팩토리 함수, 가짜 생성자, 팩토리 클래스의 메서드로 팩토리 함수를 구성할 수 있다.

## Companion 객체 팩토리 함수

팩토리 함수를 정의하는 가장 일반적인 방식은 바로 Companion 객체를 사용하는 것이다.

```kotlin
class MyLinkedList<T>(
	val head: T,
	val tail: MyLinkedList<T>?
): MyList<T> {
	// ...
}

interface MyList<T> {
	companion object {
		fun <T> of(vararg elements: T): MyList<T>? {
			// ...
		}
	}
}
```

위와 같이 companion object에 팩토리 함수를 정의하는 것이다. Java에서 정적 팩토리 메서드에 사용하는 이름을 보통 사용한다.

## 확장 팩토리 함수

만약 Companion 객체가 존재하는 경우, 이 객체의 함수처럼 사용할 수 있는 팩토리 함수를 만들어야 할 수 있다. 예를 들어 Companion 객체를 직접 수정할 수 없고 다른 파일에 함수를 만들어야 하는 경우이다. 이 경우는 확장함수를 정의하면 된다.

```kotlin
interface Tool {
	companion object {
		// ... 
	}
}
```

위 Tool 인터페이스는 수정이 불가한 인터페이스라고 가정한다. 이때 companion object가 존재하므로 확장함수를 정의할 수 있다.

```kotlin
fun Tool.Companion.createBigTool( /* ... */ ): BigTool {
	// ...
}
```

위와 같이 확장함수로 팩토리 함수를 정의할 수 있다. 위 확장할수는 `Tool.createBigTool()`로 사용할 수 있다. 단, Companion 객체에 확장함수를 정의하려면 companion object가 정의되어 있어야 한다.

## 톱레벨 팩토리 함수

객체를 만드는 흔한 방법 중 하나로 톱레벨 팩토리 함수를 이용하는 방법이 있다. Kotlin 표준 라이브러리에서 제공하는 `listOf`, `setOf`, `mapOf`가 톱레벨 팩토리 함수의 대표적인 예시이다.

```kotlin
public fun <T> listOf(vararg elements: T): List<T> = if (elements.size > 0) elements.asList() else emptyList()
```

단, 톱레벨 팩토리 함수는 모든 곳에서 사용할 수 있다. 때문에 함수의 이름을 클래스 메서드 이름처럼 선언하면 혼란을 초래할 수 있다. 따라서 톱레벨 함수는 신중하게 잘 지정해야한다.

> 때문에 톱레벨 팩토리 함수는 최대한 구체적으로 지정해야하지 않나 생각한다.

## 가짜 생성자

Kotlin의 생성자는 톱레벨 함수와 같은 형태로 사용된다.

```kotlin
class A
val a = A()
```

때문에 생성자는 톱레벨  함수처럼 참조될 수 있다.

```kotlin
val reference: () -> A = ::A
```

이렇게 대문자로 시작하는지 시작하지 않는지는 함수냐 생성자냐를 나누는 기준이 된다. 물론 함수도 대문자로 선언해도 컴파일상으로는 문제가 없다. 단, 일반적으로는 생성자와 같이 객체를 생성하는 함수에 대해서 대문자로 선언해야한다.

이런 기법 때문에 인터페이스 List나 MutableList도 생성자처럼 동작하는 함수를 가질 수 있다.

```kotlin
public inline fun <T> List(size: Int, init: (index: Int) -> T): List<T> = MutableList(size, init)

public inline fun <T> MutableList(size: Int, init: (index: Int) -> T): MutableList<T> {
    val list = ArrayList<T>(size)
    repeat(size) { index -> list.add(init(index)) }
    return list
}
```

왜냐면 Kotlin 1.1 버전부터 위와 같은 함수를 지원하기 때문이다. 생성자는 아니지만 생성자처럼 동작하므로 가짜 생성자라고 부른다. 보통 가짜 생성자는 인터페이스에 생성자를 부여하고 싶을때나 reified 타입의 인자를 갖게 하고 싶을 때 사용한다.

참고로 Companion 객체에 invoke 함수를 정의하여 가짜 생성자를 만들 수도 있지만 이 방법은 추천하지 않는다. invoke의 의미에 위반되기 때문이다.

## 팩토리 클래스의 메서드

팩토리 클래스는 클래스의 상태를 가질 수 있다는 특성 때문에 팩토리 함수보다 다양한 기능을 갖는다. 따라서 캐싱이나 이전에 만든 객체를 복제해서 객체를 생성하는 방법 등으로 사용할 경우 팩토리 클래스를 선언하는 방법도 있다.

**Comment by hyenny** [comment]
### 팩토리 함수?
- 생성자의 역할을 대신 해 주는 함수

### 팩토리 함수 장점
- **생성자와 다르게, 함수에 이름을 붙일 수 있다.**
    - 이름은 객체가 생성되는 방법과 아규먼트로 무엇이 필요한지 설명할 수 있다.
    - 생성자 : Array List(3)
        - 3이 무엇을 의미? 새로 생성하는 리스트의 첫 번째 요소? 리스트의 크기?
    - 팩토리 함수 : ArrayList.withSize(3)
        - 리스트 크기가 3인 ArrayList
    - 이름이 붙어 있으면 이해하기 쉽고 동일한 파라미터 타입을 갖는 생성자의 충돌을 줄일 수 있다.
- 생성자와 다르게, 함수가 원하는 형태의 타입을 리턴할 수 있다. 따라서 다른 객체를 생성할 때 사용할 수 있다.
    - ex. 인터페이스 뒤에 실제 객체의 구현을 숨길 때
- **생성자와 다르게, 호출될 때마다 새 객체를 만들 필요가 없다.**
    - 함수를 사용해서 객체를 생성하면 싱글턴 패턴처럼 객체를 하나만 생성하게 강제하거나 최적화를 위해 캐싱 메커니즘을 사용할 수도 있다.
    - 또한 객체를 만들 수 없을 경우 null을 리턴하게 만들 수도 있다.
        - ex. Connection.createOrNull() 어떤 이유로 연결을 생성할 수 없을 때 null을 리턴한다.
- 팩토리 함수는 아직 존재하지 않는 객체를 리턴할 수도 있다.
- 객체 외부에 팩토리 함수를 만들면, 그 가시성을 원하는 대로 제어할 수 있다.
    - ex. 톱레벨 팩토리 함수를 같은 파일 또는 같은 모듈에서만 접근하게 만들 수 있다.
- 팩토리 함수는 인라인으로 만들 수 있으며, 그 파라미터들을 refied로 만들 수 있다.
- 팩토리 함수는 생성자로 만들기 복잡한 객체도 만들어 낼 수 있다.
- 생성자는 즉시 슈퍼클래스 또는 기본 생성자를 호출해야 한다. 하지만 팩토리 함수를 사용하면, 원하는 때에 생성자를 호출할 수 있다.

### 생각
팩토리 함수 사용해라.. companion 객체 팩토리 함수 말고 다른 경우는 언제 사용할까
