### ISSUE TITLE
Item 34. 기본 생성자에 이름 있는 옵션 아규먼트를 사용하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#34]
`Item 34. 기본 생성자에 이름 있는 옵션 아규먼트를 사용하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
객체를 정의하고 생성하는 방법을 지정할 때 사용하는 가장 기본적인 방법은 기본 생성자를 이용하는 것이다.

Java에서는 이름 있는 옵션 아규먼트를 지원하지 않았기 때문에 점층적 생성자 패턴과 빌더 패턴이 성행했지만 Kotlin에서는 굳이 사용할 필요가 없다. 오히려 코드가 장황해질 뿐이다.

Kotlin에서는 이름 있는 옵션 아규먼트를 지원하기 때문에 이를 사용하여 기본 생성자를 활용하는 것이 보다 좋다. 더 짧고 명확하면서 사용하기 좋기 때문이다.

**Comment by hyenny** [comment]
### 결론
- 디폴트 아규먼트와 이름 있는 아규먼트를 사용하자

### 디폴트 아규먼트가 점층적 생성자보다 좋은 이유
- 파라미터들의 값을 원하는 대로 지정할 수 있다.
- 아규먼트를 원하는 순서로 지정할 수 있다.
- **명시적으로 이름을 붙여서 아규먼트를 지정하므로 의미가 훨씬 명확하다.**

### 빌더 패턴보다 이름 있는 파라미터가 좋은 이유
- 디폴트 아규먼트가 있는 생성자 또는 팩토리 메서드가 빌더 패턴보다 구현하기 쉽다 (더 짧다)
- 객체가 어떻게 생성되는지 생성자 주변의 디폴트 아규먼트 코드를 보면 된다.
- 빌더 패턴은 추가적인 knowedge가 필요하지만 기본 생성자는 언어에 내장된 개념이다.
- 코틀린 함수 파라미터는 항상 immutable이므로 동시성 관련된 문제가 없다
