### ISSUE TITLE
Item 36. 상속보다는 컴포지션을 사용하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#36]
`Item 36. 상속보다는 컴포지션을 사용하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
상속은 객체지향의 핵심 기능으로 소개될만큼 강력한 기능이다. 단, 잘못 사용하면 유지보수에 매우 심각한 상황을 초래한다.

상속은 “is-a” 관계의 객체 계층 구조를 만들때 사용해야한다. 상속 관계가 명확하지 않을 때 사용하게 되면 여러 문제가 발생할 수 있다. 때문에 코드 추출, 재사용을 위해서 상속 사용을 고려한다면 다시 한 번 생각해보는 것이 좋다. 그리고 코드 추출과 재사용을 위한 것이라면 컴포지션이 보다 나은 선택이다.

상속은 상위 클래스의 모든 것을 받는다. 만약 상위 클래스를 구현한 여러 클래스에서 따로 로직을 정의하지 않는 경우가 있다면 상속이 적절한지를 고민해봐야한다. 또한 하위 클래스의 캡슐화를 깰 수 있다. 상위 클래스의 구현이 변경되면 하위 클래스 또한 변경되기 때문이다.

# Override 제한

Kotlin에서는 기본적으로 상위 구현 클래스의 메서드는 재정의가 불가하다. 단, `open` 키워드로 하위 클래스에서 재정의가 가능하도록 변경할 수 있다.

```kotlin
open class Person(
	val name: String,
) {
	open fun hello() {
		println("hello world!")
	}
}

open class Pkch: Person("pkch") {
	override fun hello() {
		println("hello $name")
	}
}
```

위와 같이 `Person#hello`를 하위 클래스에서 재정의가 가능하다.

그리고 하위 서브 클래스에서 재정의한 메서드를 더이상 재정의하지 못하도록 만들고 싶을 수 있다. 이를 위해서 `final` 키워드를 사용할 수 있다.

```kotlin
open class Person(
	val name: String,
) {
	open fun hello() {
		println("hello world!")
	}
}

open class Student: Person("pkch") {
	final override fun hello() {
		println("hello student")
	}
}

class Pkch: Student("pkch") {
	override fun hello() { // error
		println("hello $name")
	}
}
```

**Comment by hyenny** [comment]
### 상속의 단점
- 상속은 **하나의 클래스만을 대상**으로 할 수 있다. 상속을 사용해서 행위를 추출하다 보면, 많은 함수를 갖는 거대한 BaseXXX 클래스를 만들게 되고, 굉장히 깊고 복잡한 계층 구조가 만들어진다.
- 상속은 클래스의 모든 것을 가져오게 된다. 따라서 **불필요한 함수를 갖는 클래스가 만들어질 수 있다.**
    - 인터페이스 분리 원칙 위반
- 상속은 이해하기 어렵다. 일반적으로 개발자가 메서드를 읽고, 메서드의 작동 방식을 이해하기 위해 슈퍼클래스를 여러 번 확인해야 한다면, 문제가 있는 것이다.

이러한 이유 때문에 상속보단 컴포지션을 사용하는 것이 좋다.

### 컴포지션
- 객체를 프로퍼티로 갖고, 함수를 호출하는 형태로 사용하는 것

```
class Progress {
	fun showProgress() { /* show progress */ }
	fun hideProgress() { /* hide progress */}
}


class ProfileLoader {
	val progress = Progress()

	fun load() {
		progress.showProgress()
		// 프로파일을 읽어 들임
		progress.hideProgress()
	}
}

class ImageLoader {
	val progress = Progress()

	fun load() {
		progress.showProgress()
		// 이미지를 읽어 들임
		progress.hideProgress()
	}
}
```
- progress 바를 더 자유롭게 사용할 수 있다.

```
class ImageLoader {
	private val progress = Progress()
	private val finishedAlert = FinishedAlert()

	fun load() {
		progress.showProgress()
		// 이미지를 읽어 들임
		progress.hideProgress()
		finishedAlert.show()
	}
}
```
- 하나의 클래스 내부에서 여러 기능(progress, alert)을 재사용할 수 있다.
- 컴포지션은 필요한 것만 받을 수 있다. 

### 모든 것을 가져오는 상속
```
class ImageLoader {
	private val progress = Progress()
	private val finishedAlert = FinishedAlert()

	fun load() {
		progress.showProgress()
		// 이미지를 읽어 들임
		progress.hideProgress()
		finishedAlert.show()
	}
}
```
- 로봇 강아지를 만들고 싶은데 로봇 강아지는 bark(짖기)만 가능, sniff(냄새 맡기)는 못하게 하려면?

```
class Labrador: Dog()

class RobotDog: Dog() {
	override fun sniff() {
		throw Error("Operation not supported")
		// 인터페이스 분리 원칙에 위반됨
	}
}

```

### 상속을 사용해야 하는 경우
→ 명확한 ‘is-a 관계’일 때 
- 슈퍼클래스를 상속하는 모든 서브클래스는 슈퍼클래스로도 동작할 수 있어야 한다.
- 슈퍼클래스의 모든 단위 테스트는 서브클래스로도 통과할 수 있어야 한다 (리스코프 치환 원칙)
