### ISSUE TITLE
Item 4. inferred 타입으로 리턴하지 말라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#4]
`Item 4. inferred 타입으로 리턴하지 말라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by aegis1920** [comment]
### 정리 및 내 생각

- 타입 추론을 하지말고 명시적으로 타입을 지정하자
- 그럼 타입 추론은 언제 써야 적당할까?
  - public으로 선언된 것들은 명시적으로 타입을 작성하면 좋지 않을까?
  - 변수는 사용하지 않고 리턴 타입은 명시하는 형태는 어떨까

**Comment by pkch93** [comment]
**_코틀린의 타입 추론은 피연산자에 맞게 추론한다._**

Kotlin은 타입 추론시 인터페이스, 추상클래스로 추론하지 않고 해당 클래스의 타입을 그대로 추론한다.

```kotlin
open class Animal
class Zebra: Animal()

fun main() {
	var animal = Zebra()
	animal = Animal() // error
}
```

위 예시처럼 animal은 Animal의 구현체 Zebra로 할당했지만 Animal이 아닌 Zebra로 타입이 추론되었기 때문에 상위 클래스인 Animal 인스턴스가 할당될 수 없다.

**_추론 타입이 아닌 타입을 명시하자_**

위 문제는 타입을 명시하여 간단하게 해결할 수 있다.

```kotlin
open class Animal
class Zebra: Animal()

fun main() {
	var animal: Animal = Zebra()
	animal = Animal() // OK
}
```

이제 `Animal`로 지정이 되었기 때문에 변수 `animal`에도 `Zebra` 뿐만 아니라 `Animal`도 할당이 가능하다.

**Comment by cmg1411** [comment]
### 코틀린의 타입 추론은 상위 클래스 또는 인터페이스가 아닌 자신 클래스로 추론된다.

```
interface Car()

val DEFAULT_CAR: Car = Flat126P()

interface CarFactory {
    fun produce() = DEFAULT_CAR 
}
```
- 위 코드의 CarFactory 의 produce 는 Car 를 반환한다. produce() 는 Car 하위 클래스를 반환할 수 있다.
- 누군가 실수로 `val DEFAULT_CAR = Flat126P()` 로 타입 추론을 하게 되면, `val DEFAULT_CAR: Flat126P = Flat126P()` 와 같이 된다.
- 따라서 produce() 는 Flat126P 타입만을 반환할 수 있게 된다.

다형성이 필요한 경우에는 타입을 명시해줘야 실수를 막을 수 있다.
