### ISSUE TITLE
Item 45. 불필요한 객체 생성을 피하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#45]
`Item 45. 불필요한 객체 생성을 피하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by rockjoon** [comment]
# 아이템 45 불필요한 객체 생성을 피하라

## 원시타입 vs wrap타입
* 객체는 더 많은 용량을 차지함
  * Integer vs int 기준으로 20byte vs 4byte 로 5배차이
* 캡슐화 되어있을 경우 추가적인 함수 호출 필요
* 객체 생성에도 비용이 소모됨

## 객체 선언
* LinkedList를 구현할 때 마지막 노드가 비었다는 것을 표현해야 하는데,  
이럴 때 Nothing을 이용할 수 있다.
  * Nothing 은 모든 클래스의 서브타입이기 때문에 LinkedList<Nothing>은  
리스트가 covariant일 때(out) 모든 LinkedList의 서브타입이 된다.

## 캐시를 활용하는 팩토리 함수
* 재귀 함수 구현 시 메모이제이션에서 캐쉬를 활용할 수 있음.

>참고 : 책에서(p310) 나온 메모이제이션 예제는 재귀 함수와 캐쉬의 올바른 사용법이 아니다.
> 실제로 재귀함수는 다음과 같이 파라미터를 통해 캐쉬를 전달한다.
```kotlin
tailrec fun fiboFP(n: Int, first: Int, second: Int): Int =
    when (n) {
        0 -> first
        1 -> second
        else -> fiboFP(n - 1, second, first + second)
    }
```

## 무거운 객체를 외부 스코프로 보내기

```kotlin
fun <T: Comparable<T>> Iterable<T>.countMax(): Int =
    count { it == this.max() }
```
여기서 this.max() 함수를 모든 이터러블 요소마다 실행하는 것은 낭비이다. 다음과 같이 변경할 수 있다.
```kotlin
fun <T: Comparable<T>> Iterable<T>.countMax(): Int = {
    val max = this.max()
    return count { it == max }
}
```

## 지연 초기화
* 지연 초기화는 객체가 무거울 때 효율적이다.
* 다만 미리 객체를 만들어놔야 빠른 처리가 가능한 경우에는 별로 좋지 않다.(ex: http 응답)

## 기본 자료형 사용하기
* 코틀린에서 Int는 nullable이거나 타입파라미터로 쓰일 경우 Integer로 사용된다.
* 반복문 내부에서 Integer를 Int로 대체할 수 있다면 대체하는 것이 좋다.


## 개인적 생각
> 최적화를 잘 하는 것은 진정한 고수라고 생각한다.  
> 섣부른 최적화는 코드를 오염시키고, 가독성을 떨어뜨린다.  
> 또한 기술의 발달로 과거에 비해 최적화의 효용성이 상대적으로 낮아졌다.  
> 
> 따라서 최적화를 위해서는 해당 기술에 대해 깊이 알고 있어야하고,  
> 최적화와 다른 가치들 사이에서 가치판단을 할 줄 알아야 하는 매우 고난이도의 작업이다.  
> 그래서 애매한 최적화는 안하느니만 못하다는 말이 나오는 것 같다.

**Comment by pkch93** [comment]
객체 생성은 비용이 들어간다. 상황에 따라서는 굉장히 큰 비용이 들기 때문에 불필요한 객체 생성을 피하는 것이 최적화 관점에서는 좋을 수 있다.

> 여기서 비용이란 객체를 생성하는데 사용하는 컴퓨터 자원을 의미한다고 생각한다. 객체 생성에는 CPU나 메모리가 소요될 것이다.

# 객체 생성 비용

객체 생성시에는 다음과 같은 세 가지 비용이 발생한다.

1. 현재 64비트 JDK에서 객체는 8바이트의 배수만큼 공간을 차지한다. 이때 앞부분 12바이트는 헤더로써 반드시 있어야 하기 때문에 객체는 최소 16바이트를 가진다. 여기서 객체에 대한 참조 공간도 필요하다. 참조 공간은 4바이트를 가진다. 이때 참조 공간은 32비트나 64비트 JDK 모두 동일하게 4바이트를 가진다.
    
    > JVM 객체의 구체적인 필드 크기 확인이 필요하다면 [[Java Object Layout](https://plugins.jetbrains.com/plugin/10953-jol-java-object-layout)](https://plugins.jetbrains.com/plugin/10953-jol-java-object-layout)을 사용할 것을 추천

2. 요소가 캡슐화되어 있다면 접근에 추가적인 함수 호출이 필요하다. 함수를 사용하는 처리는 굉장히 빠르기 때문에 큰 비용이 들지는 않지만 이 객체 생성이 매우 많다면 비용도 굉장히 커질 수 있다.
3. 객체 생성 후 사용을 위해 메모리에서 관리한다. 즉, 메모리 공간을 사용한다는 의미이다.

객체 생성 비용에서 불필요한 객체 생성을 피하고 재사용한다면 첫 번째, 세 번째 비용은 피할 수 있다.

# 객체 생성과 관련된 최적화 기법들

## 객체 재사용하기

- object
    
    Kotlin에는 언어 문법적으로 싱글톤 객체를 만들 수 있도록 지원한다. 바로 객체 선언 `object declaration`이다. 
    
- 캐시 활용하는 팩토리 함수

## 무거운 객체 외부 스코프로 보내기

성능을 위한 유용한 트릭 중 하나로 무거운 객체를 외부 스코프로 보내는 방법이 있다. 컬렉션 처리에서 이뤄지는 무거운 연산은 컬렉션 처리 함수 내부에서 외부로 빼내는 것이 좋다.

```kotlin
fun <T: Comparable<T>> Iterable<T>.countMax(): Int =
	count { it == this.max() }
```

위와 같이 Iterable 내부에 최대값의 수를 새는 확장 함수를 만드는 경우가 있다고 가정한다. 이때 수를 셀때마다 `Iterable#max`를 호출한다. 이는 재사용을 통해 최적화가 가능해보인다.

```kotlin
fun <T: Comparable<T>> Iterable<T>.countMax(): Int {
	val max = this.max()
	return count { it == max }
}
```

이렇게 매번 비용이 발생하는 `Iterable#max`를 count 스코프 내에서 바깥으로 뺌으로써 최적화를 했다.

> 위 패턴이 가장 널리 사용하는 사례가 `String#matches`를 사용하는 것에서 Pattern을 정의해놓고 재사용하는 사례이다.

## 지연 초기화

생성에 매우 큰 비용이 드는 객체가 있을 수 있다. 어떤 클래스 A에서 B, C, D라는 무거운 인스턴스가 필요할 때 A를 생성하면서 B, C, D를 모두 생성하는 것은 매우 큰 부담이다. 이를 최적화하기 위해 지연 초기화를 사용할 수 있다.

> Kotlin에서는 기본적으로 프로퍼티 위임을 통해 지연 초기화를 지원하고 있다.

단, 지연 초기화는 상황에 따라 오히려 역효과를 낳을 수 있다. 특히 지연 초기화를 사용하면 첫 호출때 생성하는 시간이 필요하므로 응답이 매우 느릴 수 있다. 그리고 성능 테스트 시에도 복잡해지는 문제가 있으므로 상황에 맞게 적용해야한다.

## 기본 자료형 활용하기

기본 자료형을 위한 최적화도 가능하다. 단, 이 최적화는 Kotlin/JVM과 일부 Kotlin/Native에서만 유효하며 이마저도 숫자에 대한 작업이 여러 번 반복될 때만 유효하다. 그리고 기본 자료형은 언어에서 제공한 기능만을 사용해야하므로 기존에 사용하던 클래스에서 기본 자료형으로 변경한다면 가독성이 떨어질 수도 있다.

따라서 코드나 라이브러리의 성능이 굉장히 중요한 경우에만 사용을 권장한다.

```kotlin
fun Iterable<Int>.maxOrNull(): Int? {
	var max: Int? = null
	for (i in this) {
		max = if (i > max ?: Int.MIN_VALUE)) i else max
	}
	return max
}

fun Iterable<Int>.maxOrNull(): Int? {
	val iterator = iterator()
	if (!iterator.hasNext()) return null
	var max: Int = iterator.next()
	while (iterator.hasNext()) {
		val e = iterator.next()
		if (max < e) max = e
	}
	return max
}
```

Iterable에 100 ~ 1000만개의 데이터를 넣고 테스트하면 전자 예시보다 후자의 예시가 2배는 빠르다. 그 이유는 전자는 nullable을 다뤄야하므로 Integer를 사용했고 후자는 Int 기본 자료형을 사용했기 때문이다.
