### ISSUE TITLE
Item 46. 함수 타입 파라미터를 갖는 함수에 inline 한정자를 붙여라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#46]
`Item 46. 함수 타입 파라미터를 갖는 함수에 inline 한정자를 붙여라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by rockjoon** [comment]
# item 46 함수 타입 파라미터를 갖는 함수에 inline한정자를 붙여라.

## 함수에 inline 한정자를 사용하는 것의 장점

### 1. reified 한정자 사용 가능
* type erasure 때문에 런타임에서 타입정보를 알 수 없지만, reified 한정자를 붙이면  
type parameter가 type argument로 대체되기 때문에 타입정보를 사용할 수 있음.

### 2. 함수 타입 파라미터를 가진 함수가 훨씬 빠르게 동작
* 함수 호출과 리턴을 위해 점프하는 과정이 생략됨.
* jvm에서 함수를 다루는 방식은 함수 - 객체 변환 방식이기 때문에, 객체 변환 비용이 절약됨.

## inline 한정자의 비용
* 재귀 방식으로 사용될 경우 무한 증식
* 내부에서 private/internal 가시성을 가진 함수와 프로퍼티 사용불가
* 인라인 함수가 인라인 함수를 호출할 경우 생성되는 코드량이 많아짐.

## inline함수가 사용되는 주요 사례
* print와 같이 매우 자주 사용되는 함수
* reified 한정자와 같이 사용되는 경우
* 함수 타입 파라미터를 갖는 함수 - 특히 컬렉션 관련 함수, 스코프 함수, 유틸리티 함수 등

**Comment by pkch93** [comment]
inline 한정자는 컴파일 시점에 **함수를 호출하는 부분에서 함수의 본문으로 대체**시킨다.

```kotlin
inline fun repeat(times: Int, action: (Int) -> Unit) {
	for (index in 0 until times) {
		action(index)
	}
}
```

위 repeat은 Kotlin 표준 라이브러리에 정의되어있는 함수이다. 위 코드에서 inline 한정자가 붙어있는 것을 알 수 있다.

```kotlin
repeat(10) { print(10) }
```

따라서 inline 함수 repeat을 호출하는 코드는 아래와 같이 컴파일 시점에 대체된다.

```kotlin
for (index in 0 until 10) {
	print(index)
}
```

이를 통해 repeat을 호출하는 비용없이 repeat 로직을 사용한다. 이 로직이 inline 함수의 기본 동작이다.

# inline의 장점

inline 한정자를 사용하면 다음과 같은 장점이 있다.

1. 타입 아규먼트에 reified 한정자를 붙여서 사용할 수 있다.
2. 함수 타입 파라미터를 가진 함수가 훨씬 빠르게 동작한다.
3. 비지역 `non-local` 리턴을 사용할 수 있다.

## 타입 아규먼트에 reified 한정자를 붙여서 사용할 수 있다.

초기 Java에서는 제네릭이 존재하지 않았다. Java 1.5부터 등장했던 기능이므로 Java에 제네릭을 넣을때는 하위버전을 고려하여 컴파일시에는 제네릭 타입과 관련된 내용이 제거된다. 이 때문에 타입 파라미터와 관련된 연산도 오류가 밣생한다.

```kotlin
fun <T> printTypeName() {
	print(T::class.simpleName) // ERROR
}
```

이런 문제는 inline 함수로 만들면 해결될 수 있다. 함수 호출이 본문으로 대체되기 때문에 타입 파라미터에 reified 한정자를 사용하여 타입 아규먼트로 실체화할 수 있다.

```kotlin
inline fun <reified T> printTypeName() {
	print(T::class.simpleName) // OK
}
```

컴파일하는 동안 printTypeName의 본문에 T 타입 인자가 실체화된다. 따라서 컴파일 이후에도 해당 타입을 알 수 있기 때문에 오류가 발생하지 않는다.

## 함수 타입 파라미터를 가진 함수가 훨씬 빠르게 동작한다.

기본적으로 함수 호출 과정이 사라지기 때문에 모든 함수에서 빠르게 동작할 수 있다. 단, 함수 파라미터를 가지지 않는 함수에서는 큰 성능 차이를 보이지는 않는다. 이는 함수를 객체로 조작할 때 발생하는 문제를 알아야 이해할 수 있다.

### 함수를 객체로 조작하는 방법

Kotlin/JS와 달리 Kotlin/JVM에서는 JVM 익명 클래스 또는 일반 클래스를 기반으로 함수를 객체로 만든다.

```kotlin
val lambda: () -> Unit = {}
```

위 함수 파라미터를 갖는 Kotlin 코드를 컴파일하면 아래와 같은 결과가 나온다.

```java
Fuction0<Unit> lambda = new Function0<Unit>() {
	public Unit invoke() {}
};
```

참고로 JVM에서 인자가 없는 함수 타입은 `Function0` 타입으로 변환된다. 따라서 `Function0`을 생성하는 것이다. 이렇게 Kotlin/JVM에서는 함수 타입을 지정하며 함수 `lambda`를 선언하지만 실제로는 객체를 생성한다. 때문에 함수 파라미터를 사용하는 경우 객체를 생성하는 비용이 추가되는 것이다.

### 인라인 함수의 또다른 이점 - 지역변수 캡쳐

인라인 함수와 인라인이 아닌 함수의 차이는 함수 리터럴 내부에서 지역 변수를 캡쳐할 때 확인할 수 있다. 캡쳐된 값은 객체로 래핑해야하며 사용할 때마다 객체를 통해 작업이 이뤄져야한다.

```kotlin
var l = 1L
noinlineRepeat(100_000_000) {	l += it }
```

인라인이 아닌 람다에서는 지역변수 l을 직접 사용할 수 없다. 때문에 Kotlin에서는 지역변수 l을 함수 리터럴 내에서 사용할 수 있도록 하기 위해 컴파일 과정에 레퍼런스 객체로 래핑한다.

```kotlin
val a = Ref.LongRef()
a.element = 1L
noinlineRepeat(100_000_000) {	a.element += a.element + it }
```

즉, 인라인이 아닌 함수에서는 지역 변수를 래핑하는 객체를 생성하기 때문에 인라인 함수보다 더 큰 비용이 든다. 따라서 함수 파라미터를 가진 함수는 인라인으로 지정하는 것이 좋다.

## 비지역 리턴을 사용할 수 있다.

인라인 함수를 사용함으로써 얻는 이점 중에 하나는 비지역 리턴이 가능하다는 것이다. 인라인이 아닌 함수는 비지역 리턴이 불가한데 이는 함수가 객체로 래핑되기 때문이다. 즉, 함수가 다른 클래스에 위치하기 때문에 `return`을 통해 실제 선언한 함수로 돌아올 수 없기 때문이다.

```kotlin
fun main() {
	repeatNoinline(10) { 
		print(it)
		return // ERROR
	}
}
```

즉, 위 예시에서는 인라인이 아닌 함수의 함수 리터럴에서 `return`이 허용되지 않는다. 이런 문제는 인라인 함수로 선언한다면 제한이 없다. 함수가 컴파일시에 그대로 본문으로 대체되기 때문이다.

```kotlin
fun main() {
	repeat(10) { 
		print(it)
		return // OK
	}
}
```

코틀린에서 제공하는 repeat은 inline 함수이므로 `return`이 허용된다.

# inline의 단점

inline 한정자는 매우 유용하지만 모든 곳에 사용은 불가하다.

### 재귀 함수로 사용 불가

인라인 함수는 재귀적으로 사용이 불가하다. 재귀적으로 사용하면 무한하게 대체되므로 문제가 발생할 수 있다. 또한 이는 IDE에서도 잡아주지 못하기 때문에 심각한 문제를 초래할 수 있다.

### 특정 가시성 제한 요소 사용 불가

public 인라인 함수 내부에서는 private과 internal 가시성을 가지는 함수와 프로퍼티 사용이 불가하다.

```kotlin
internal inline fun read() {
	val reader = Reader() // ERROR
	// ...
}

private class Reader { /* ... */ }
```

인라인 함수는 구현을 숨길 수가 없기 때문에 클래스에서는 거의 사용되지 않는다.

### 코드의 크기가 쉽게 커질 수 있다.

인라인 함수를 호출하는 인라인 함수가 많아지면 코드의 크기가 비대해질 수 있다.

```kotlin
inline fun printThree() { print(3) } 
```

3을 프린트하는 printThree가 있다고 가정한다. 여기서 3을 여러번 호출하기 위해서 다음과 같이 추가 인라인 함수를 정의한다.

```kotlin
inline fun threePrintThree() { 
	printThree()
	printThree()
	printThree()
}

inline fun threeThreePrintThree() { 
	threePrintThree()
	threePrintThree()
	threePrintThree()
}

inline fun threeThreeThreePrintThree() { 
	threeThreePrintThree()
	threeThreePrintThree()
	threeThreePrintThree()
}
```

위 코드들은 다음과 같이 컴파일 된다.

```kotlin
inline fun printThree() { print(3) } 

inline fun threePrintThree() { 
	print(3)
	print(3)
	print(3)
}

inline fun threeThreePrintThree() { 
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
}

inline fun threeThreeThreePrintThree() { 
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
	print(3)
}
```

> 비대한 코드는 컴파일 타임을 증가시키고 런타임에 더 많은 메모리를 사용하므로 애플리케이션의 성능을 저하시킨다.
> 

# crossinline과 noinline

함수를 인라인으로는 만들고 싶지만 일부 함수 타입의 파라미터는 inline으로 받고 싶지 않을 수 있다. 이를 위해 코틀린에서는 crossinline과 noinline을 지원한다.

- crossinline
    
    인자로 인라인 함수를 받지만 비지역적 리턴을 하는 함수는 받지 못한다. 인라인으로 만들지 않은 다른 람다 표현식과의 조합해서 사용할 때 문제가 발생하는 경우 활용할 수 있다.
    
- noinline
    
    인라인 함수를 받지 못하도록 만든다. 함수를 아규먼트로 사용하고 싶을 때 활용한다.
    

```kotlin
inline fun requestNewToken(
	hasToken: Boolean,
	crossinline onRefresh: () -> Unit,
	noinline onGenerate: () -> Unit,
) {
	if (hasToken) {
		httpCall("get-token", onGenerate)
		// inline이 아닌 httpCall에서 인자로 함수를 전달하기 위해서는 noinline인 함수가 필요하다.
	} else {
		httpCall("refresh-token") {
			onRefresh()
			// inline이 아닌 httpCall의 함수와 함께 사용하기 위해서는 crossinline이나 noinline이 필요하다.
			onGenerate()
		}
	}
}

fun httpCall(url: String, callback: () -> Unit) {	/* ... */ }
```

**Comment by hyenny** [comment]
## inline 한정자 사용시 장점
1. 타입 아규먼트에 reified 한정자를 붙여서 사용할 수 있다.
2. **함수 타입 파라미터를 가진 함수가 훨씬 빠르게 동작한다.**
3. non-local 리턴을 사용할 수 있다.

### 함수 타입 파라미터를 가진 함수가 훨씬 더 빠르게 동작한다.
- 모든 함수는 inline 한정자를 붙이면 조금 더 빠르게 동작한다. -> 함수 호출과 리턴을 위해 점프하는 과정과 백스택 추적하는 과정이 없기 떄문! (그래서 표준 라이브러리의 간단한 함수 대부분 inline 한정자가 붙어 있음)
- 하지만 함수 파라미터를 가지지 않는 함수는 이러한 처리가 큰 성능 차이를 발생시키지 않는다.

## inline 한정자 사용시 단점
- inline 한정자는 모든 곳에 사용할 수 없다. 
ex. 재귀적으로 동작 x 재귀적으로 사용하면 무한하게 대체되는 문제가 발생하지만 인텔리제이가 오류로 잡아주지 못한다고..
- inline 함수는 더 많은ㅇ 가시성 제한을 가진 요소를 사용할 수 없다
- inline 한정자를 남용하면 코드의 크기가 쉽게 커진다. 

## inline 함수가 사용되는 주요 사례

- print 함수처럼 매우 많이 사용하는 경우
- filterIsInstance 함수처럼 타입 아규먼트로 reified 타입을 전달받는 경우
- 함수 타입 파라미터를 갖는 톱레벨 함수를 정의해야 하는 경우.
    - 컬렉션 처리 함수와 같은 헬퍼 함수(map, filter, flatMap, joinToString 등)
    - 스코프 함수(also, apply, let 등)
    - 톱레벨 유틸리티 함수(repeat, run, with)
