### ISSUE TITLE
Item 47. 인라인 클래스의 사용을 고려하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#47]
`Item 47. 인라인 클래스의 사용을 고려하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by rockjoon** [comment]
# item 47 인라인 클래스의 사용을 고려하라.

## 단위를 표현할 때
```kotlin
inline class Minute(val minutes: Int){
    //...
}

inline class Millis(val milliseconds: Int){
  //...
}
```
* 예제에서 두 인라인 클래스 모두 int형의 프로퍼티를 담고 있지만, 각각 다른 타입을 가지고 있기  때문에 단위의 혼재를 막을 수 있다. (컴파일러가 체크할 수 있다.)
* 동시에 inline클래스는 컴파일 시 내부 property로 대체되기 때문에 wraping에 대한 비용이 들지 않는다.
* 즉, 개발자에게는 타입을 구분하게 해주고, 컴퓨터에게는 같은 타입이라고 알려주기 때문에
타입 안정성과 비용 효율성을 모두 챙길 수 있다.

## 타입 오용으로 발생하는 문제를 막을 때
```kotlin
inline class StudentId(val studentId: Int)
inline class TeacherId(val teacherId: Int)

class Grades(
    val studentId: StudentId,
    val teacherId: TeacherId,
)
```
* studentId와 teacherId가 모두 int이기 때문에 실수로 잘못된 값을 넣을 수도 있지만, 
inline 클래스를 사용하면 이를 방지할 수 있다.
* 

## 개인적 생각
> 장점이 많은데 비용은 거의 없는 것 같다. 한번 적극적으로 써봐야겠다.

**Comment by pkch93** [comment]
inline은 클래스에도 적용가능하다. 하나의 값을 보유하는 클래스에 사용이 가능하며 이 기능은 Kotlin 1.3부터 도입되었다.

> 단, inline 클래스는 현재 코틀린 1.8.21에서는 Deprecated 예정이다. `inline` 대신 `value` 를 사용하도록 권장하고 있다. 그리고 Kotlin/JVM에서는 `value class`에는 `@JvmInline`을 선언해야한다.
>
> [Kotlin Value Classes Design Notes](https://github.com/Kotlin/KEEP/blob/master/notes/value-classes.md) 참고 

```kotlin
@JvmInline
value class Name(
	private val value: String,
) {
	fun greet() {
		print("Hello, $value")
	}
}
```

위와 같이 하나의 프로퍼티를 가지는 클래스에 대해 inline 한정자로 선언이 가능하다. 이 경우 해당 객체를 사용하는 위치가 모두 해당 프로퍼티로 변경된다.

```kotlin
val name: Name = Name("pkch")

// 컴파일 후
val name: String = "pkch"
```

그리고 inline 클래스의 메서드는 모두 정적 메서드가 된다.

```kotlin
val name: Name = Name("pkch")
name.greet()

// 컴파일 후
val name: String = "pkch"
Name.`greet-impl`(name)
```

인라인 클래스는 다른 자료형을 래핑하여 새로운 자료형을 만들 때 사용한다. 따라서 다음과 같은 상황에서 주로 사용한다.

- 측정 단위 표현
- 타입 오용으로 발생하는 문제를 막을 때

inline 클래스는 어떠한 오버헤드도 발생시키지 않고 기본 자료형이 표현하지 못하는 부분을 클래스로 래핑하여 보다 가독성을 높일 수 있기 때문에 유용하게 사용이 가능하다.

# 인라인 클래스와 인터페이스

인라인 클래스도 일반 클래스와 마찬가지로 인터페이스 구현이 가능하다.

단, 이경우 inline의 이점을 전혀 얻을 수 없다. 왜냐면 인터페이스를 통해 타입을 나타내려면 결국 객체를 래핑해야하기 때문이다. 따라서 인터페이스를 구현하는 인라인 클래스는 아무 의미가 없다.

# typealias

코틀린은 typealias로 타입에 새로운 이름을 부여할 수 있도록 도와준다.

```kotlin
typealias NewName = Int
val n: NewName = 10
```

> 위와 같이 이미 정의된 타입에 사용하기 보다는 함수 타입에 이름을 부여할 때 보통 많이 사용하는 것 같다.

단, typealias는 안전하지 않다. 특히 위 예시에서 NewName은 Int를 표현하기 때문에 Int 대신에 사용이 가능하다.

```kotlin
val newName: NewName = 10
val age: Int = newName // OK
```

위와 같이 사용이 가능하다. 이런 문제 때문에 가독성을 해칠 수 있으며 문제 파악을 어렵게 만든다.

> typealias는 긴 타입을 간략하게 또는 가독성 있게 표현할때 정도로만 사용하는 것이 좋으며 다른 타입을 대체해서 사용하는 용도로는 추천하지 않는다.

**Comment by hyenny** [comment]
## inline 클래스
코틀린 1.3부터 기본 생성자 프로퍼티가 하나인 클래스 앞에 inline을 붙이면, 해당 객체를 사용하는 위치가 모두 해당 프로퍼티로 교체된다.

```kotlin
inline class Name(private val value: String) {
	// ...
}
```

```kotlin
// 코드
val name: Name = Name("Marcin")

// 컴파일 때 다음과 같은 형태로 바뀐다.
val name: String = "Marcin"
```

inline 클래스의 메서드는 모두 정적 메서드로 만들어진다.

```kotlin
inline class Name(private val value: String) {
	//...

	fun greet() {
		print("Hello, I am $value")
	}

}

// 코드
val name: Name = Name("Marcin")
name.greet()

// 컴파일 때 다음과 같은 형태로 바뀐다.
val name = "Marcin"
Name.'greet-impl'(name)
```

}

인라인 클래스는 다른 자료형을 래핑해서 새로운 자료형을 만들 때 많이 사용된다. 이 때 어떠한 오버헤드도 발생하지 않는다.

## inline 클래스를 사용하는 상황
- 측정 단위를 표현할 때
- **타입 오용으로 발생하는 문제를 막을 때**

```kotlin
inline class StudentId(val studentId: Int)
inline class TeacherId(val teacherId: Int)

@Entity(tableName = "grades")
class Grades(
	@ColumeInfo(name = "studentId")
	val studentId: StudentId,

	@ColumeInfo(name = "teacherId")
	val teacherId: TeacherId,
	
)
```
이렇게 하면 ID를 사용하는 것이 굉장히 안전해지며, 컴파일할 때 타입이 Int로 대체되므로 코드를 바꾸어도 별도의 문제가 발생하지 않는다.

→ 안전을 위해 새로운 타입을 도입해도, 추가적인 오버헤드가 발생하지 않는다.
