### ISSUE TITLE
Item 48. 더 이상 사용하지 않는 객체의 레퍼런스를 제거하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#48]
`Item 48. 더 이상 사용하지 않는 객체의 레퍼런스를 제거하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by rockjoon** [comment]
# item48. 더 이상 사용하지 않는 객체의 레퍼런스를 제거하라.
## 메모리 누수 방지하는 방법
* 수동으로 해제한다.
* 캐시와 같은 케이스는 SoftReference를 사용 (메모리가 부족한 경우 해제됨, 그렇지 않으면 유지)
* 대화상자와 같은 케이스는 WeakReference 사용(gc작동시 무조건 해제)
* 별도의 라이브러리 사용하여 메모리 체크
* 가장 좋은 방법은 수동으로 해제해야 하는 상황을 피하는 것
  * 스코프 최소화
  * 톱레벨 프로퍼티 또는 객체 선언으로 큰 데이터를 저장하지 않는 것

**Comment by pkch93** [comment]
Java나 Kotlin 같은 JVM 계열의 언어에서는 JVM이 가비지 컬렉션을 통해 메모리 관리를 해준다. 단, 그렇다고 모든 객체를 메모리에 놓고 참조를 유지하게 되면 사용하지 않는 객체 인스턴스들이 메모리에 그대로 남게 되므로 메모리 릭이 발생한다. 따라서 **더 이상 사용하지 않는 객체 인스턴스는 참조를 제거하여 가비지 컬렉터가 이를 수거할 수 있도록 하는 것이 중요**하다.

사실 객체를 수동으로 해제하는 경우는 굉장히 드물다. 일반적으로는 스코프를 벗어나면서 어떤 객체를 가리키는 레퍼런스가 제거될 때 객체가 자동으로 해제된다. 따라서 **메모리 관련 문제를 피하는 가장 좋은 방법은 변수를 지역 스코프에 정의하고 톱레벨 프로퍼티나 객체 선언에서 큰 데이터를 저장하지 않는 것**이다.

그리고 코드 작성시에는 메모리와 성능과 함께 가독성과 확장성을 고려해야한다. 일반적으로 가독성이 좋은 코드는 메모리와 성능적으로도 좋다. 하지만 두 요소가 상충되는 경우도 있는데 이 경우 비즈니스 애플리케이션에서는 가독성과 확장성을 더 중시하는 것이 좋다. 만약 라이브러리라면 간혹 메모리와 성능에 초점을 맞춰야할 수도 있다.

**Comment by hyenny** [comment]
### 메모리 관련된 문제를 피하는 가장 좋은 방법

객체를 수동으로 해제해야 하는 경우는 드물다고 함.
일반적으로 스코프를 벗어나면서, 어떤 객체를 가리키는 레퍼런스가 제거될 때 객체가 자동으로 해제된다. 

라이브러리 개발자는 아니기 떄문에 가독성과 확장성에 더 공감이 간다. 아래 조언 정도만 지킬 듯하다.
- **변수를 지역 스코프(local scope)에 정의**
- **톱레벨 프로퍼티 또는 객체 선언(companion 객체 포함)으로 큰 데이터를 저장하지 않는다.**
