### ISSUE TITLE
Item 49. 하나 이상의 처리 단계를 가진 경우에는 시퀀스를 사용하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#49]
`Item 49. 하나 이상의 처리 단계를 가진 경우에는 시퀀스를 사용하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
Sequence와 Iterable의 정의는 거의 동일하다.

```kotlin
interface Iterable<out T> {
	operator fun iterator(): Iterator<T>
}

interface Sequence<out T> {
	operator fun iterator(): Iterator<T>
}
```

하지만 Sequence와 Iterable의 구현 목적은 완전히 다르다.

# Sequence

시퀀스는 지연 처리된다. 시퀀스 처리 함수들을 사용하면 데코레이터 패턴으로 구현된 새로운 시퀀스가 리턴된다. 최종적인 계산은 최종 연산이 이뤄질 때 수행된다. 반면 Iterable은 처리 함수를 사용할 때마다 연산이 이뤄지고 컬렉션을 만든다.

이와 같은 시퀀스의 지연 처리를 통해 자연스런 순서 유지와 함께 최소한의 연산, 무한 시퀀스, 각각의 단계에서 컬렉션을 만들어 내지 않으므로 여러 장점을 가질 수 있다.

단, Iterable에서 Sequence로 사용하더라도 성능이 나아지지는 않는 경우가 있다. 바로 코틀린의 sorted이다. 코틀린의 sorted는 Sequence를 List로 변환한 후 자바의 sort를 사용한다. 이런 변환 처리 때문에 오히려 컬렉션보다도 Sequence가 느릴 수 있다.

여기에 무한 시퀀스처럼 Sequence의 다음 요소를 lazy하게 구하는 Sequence에 sorted를 적용하면 무한 반복에 빠진다. 때문에 이점을 기억하고 사용해야한다.

## 자연스런 순서 유지

Iterable과 Sequence의 처리는 연산 순서에 따라 다른 결과가 나온다.

```kotlin
sequenceOf(1, 2, 3)
	.filter { print("F$it, "); it % 2 == 1 }
	.map { print("M$it, "); it * 2 }
	.forEach { print("E$it, ") }
// F1, M1, E2, F2, F3, M3, E6,

listOf(1, 2, 3)
	.filter { print("F$it, "); it % 2 == 1 }
	.map { print("M$it, "); it * 2 }
	.forEach { print("E$it, ") }
// F1, F2, F3, M1, M3, E2, E6,
```

Sequence는 요소 하나하나에 지정한 연산을 모두 적용한다. 그리고 그 다음 요소에 적용한다. 반면 Iterable은 각 연산마다 모든 요소에 적용한 후 다음 연산을 적용한다. 각각 element-by-element order 또는 lazy order / step-by-step order 또는 eager order라고 부른다. 이 차이 때문에 출력 결과가 달라지는 것이다.

## 최소한의 연산

앞선 예시에서도 봤듯이 Sequence는 중간 연산 개념이 있기 때문에 최소 연산 적용이 가능하다.

```kotlin
(1..10).asSequence()
	.filter { print("$it, "); it % 2 == 1 }
	.map { print("M$it, "); it * 2 }
	.find { it > 5}
// F1, M1, F2, F3, M3,

(1..10)
	.filter { print("$it, "); it % 2 == 1 }
	.map { print("M$it, "); it * 2 }
	.find { it > 5}
// F1, F2, F3, F4, F5, F6, F7, F8, F9, F10,
// M1, M3, M5, M7, M9

```

따라서 Iterable처럼 중간 처리를 모든 요소에 적용할 필요가 없다면 Seqence를 사용하는 것이 좋다.

## 무한 시퀀스

Sequence는 실제로 최종 연산 전에는 어떤 처리도 하지 않는다. 따라서 무한 시퀀스를 만들고 필요한 부분까지만 값을 추출하는 것도 가능하다. 무한 시퀀스는 generateSeqence나 seqence를 사용하는 것이다.

```kotlin
generateSeqence(1) { it + 1 }
	.map { it * 2 }
	.take(10)
	.forEach { print("$it ,") }
// 2, 4, 6, 8, 10, 12, 14, 16, 18, 20,
```

두 번째 방법인 sequence는 코루틴을 활용한다. 따라서 suspend 함수로 요소를 지정하고 suspend 함수 내부에서 yield로 값을 하나씩 만들어낸다.

```kotlin
val fibonacci = sequence {
	yield(1)
	var current = 1
	var prev = 1
	while (true) {
		yield(current)
		val temp = prev
		prev = current
		current += temp
	}
}

print(fibonacci.take(10).toList())
// [1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
```

단, 무한 시퀀스는 값을 몇 개 활용할 지 지정하지 않으면 무한히 반복한다. 따라서 take나 first, find, any, all, none, indexOf와 같은 요소를 선택하는 종결 연산을 사용해야한다. 보통은 take와 first 정도를 사용하는 것이 좋다.

## 각각의 단계에서 컬렉션을 만들어내지 않음

Sequnce는 지연 처리를 하기 때문에 각 연산마다 컬렉션을 만들어 내지 않는다. Iterable은 각 요소마다 만들어 내기 때문에 보다 비용이 든다. 이런 이유로 파일을 처리할 때는 Sequence를 보통 사용한다.

# Java Stream과 Sequence

Java Stream도 Sequence 처럼 lazy하게 동작하여 최종 연산에서 연산이 일어난다는 점은 동일하다. 단, 다음과 같은 차이가 존재한다.

- 코틀린의 Sequence가 더 많은 처리 함수를 가짐
- Java Stream은 병렬 스트림을 지원한다.
- 코틀린의 Sequence는 Kotlin 라이브러리 모두에서 사용가능하지만 Java Stream에서는 Kotlin/JVM에서만 동작한다.

이런 차이로 병렬 기능이 필요한 경우가 아니라면 코틀린 라이브러리에서 지원하는 Sequence를 사용하는 것을 권장한다.

> Java Stream과 Kotlin Sequence는 모두 단계적으로 요소의 흐름을 추적할 수 있는 디버깅 기능을 지원한다. Java Stream은 `Java Stream Debugger`, Kotlin Sequence는 `Kotlin Sequence Debugger`로 활용할 수 있다. 참고로 현재 `Kotlin Sequence Debugger`는 `Kotlin` 플러그인에 통합되어있다.

**Comment by rockjoon** [comment]
# item 49 하나 이상의 처리 단계를 가진 경우에는 시퀀스를 사용하라.

## 시퀀스의 지연 처리(lazy)
시퀀스의 중간 연산은 최종 연산이 이루어질 때 수행 된다.
```kotlin
val seq = sequenceOf(1, 2, 3)
val filtered = seq.filter { println("f$it"); it % 2 == 1 }
println(filtered)
// 최종 연산이 행해질 때 중간연산(filter) 수행
// f1 f2 f3
val asList = filtered.toList()
println(asList)

val list = listOf(1, 2, 3)
val fList = list.filter { println("this is $it"); it % 2 == 1 } // filter가 바로 실행됨
println(fList)
```

## 순서의 중요성
시퀀스는 **각각의 요소**에 **연산을 모두** 적용  
이러터블은 **요소 전체**에 **연산을 하나씩** 적용
```kotlin
sequenceOf(1, 2, 3)
  .filter { println("f$it"); it % 2 == 1 }
  .map { println("m$it"); it * 2 }
  .forEach { println("e$it") }
//f1, m1, e2, f2, f3, m3, e6

listOf(1, 2, 3)
  .filter { println("f$it"); it % 2 == 1 }
  .map { println("m$it"); it * 2 }
  .forEach { println("e$it") }
//f1, f2, f3, m1, m3, e2, e6
```

## 최소 연산
컬렉션에 대해 연산을 적용하고 이 중 일부만 필요한 경우 시퀀스는 모든 요소에 대해 연산을 할 필요가 없다.  
```kotlin
val result = (1..10).asSequence()
  .filter { println("f$it"); it % 2 == 1 }
  .map { println("m$it"); it * 2 }
  .find { println("find$it"); it > 5 }
println(result)
// 요소별로 연산을 적용하다가 find가 true일 때 연산을 멈춤
```

## 무한 시퀀스
최종 연산이 수행될 때까지 어떤 연산도 하지 않기 때문에, 무한 시퀀스에서도 필요한 범위 만큼만 값을 가져올 수 있다.   
다만 **최종 연산에서 값을 한정해야만** 무한 반복되지 않는다.

## 각각의 단계에서 컬렉션을 만들어 내지 않음
표준 컬렉션 함수에서는 각 단계의 연산에서 새로운 컬렉션을 생성하지만,  
시퀀스는 최종 연산 때 한번에 수행하므로 컬렉션을 생성하지 않음.  


이는 **컬렉션의 크기가 크고** **연산의 단계가 많을 수록** 특히 효과적이다.

## 시퀀스가 빠르지 않은 경우
* sorted : 시퀀스를 list로 변환한 뒤자바의 sort를 사용해 처리하기 때문에 컬렉션 처리 보다 느림
* 그러나 위의 경우에도 연산의 단계가 많다면 결과적으로 시퀀스가 더 빠름.

**Comment by hyenny** [comment]
### 시퀀스 장점
- 자연스러운 처리 순서를 유지한다.
- 최소한만 연산
- 무한 시퀀스 형태로 사용할 수 있다.
- 각각의 단계에서 컬렉션을 만들어 내지 않는다.

### 시퀀스가 빠르지 않은 경우
- 코틀린 stdlib의 sorted
    - Sequence를 List로 변환한 뒤에 자바 stdlb의 sort를 사용해 처리
    
sorted 빼고 다른 처리는 모두 Sequence가 빠르므로, 여러 처리가 결합된 경우 Collection을 사용하는 것보다 Sequence를 사용하는 것이 더 빠르다. 

### 자바 스트림과 코틀린 시퀀스 차이
- 코틀린의 시퀀스가 더 많은 처리 함수를 가지고 있다. (확장 함수를 사용해서 정의되어 있으므로) 그리고 사용하기 쉽다.
    - 최종 연산을 collect(Collectors.toList())가 아닌 toList() 처럼 간단하게 할 수 있다.
- 자바 스트림은 병렬 함수를 사용해서 병렬 모드로 실행할 수 있다. 이는 멀티 코어 환경에서 굉장히 큰 성능 향상을 가져온다. 다만 몇 가지 결함이 있으므로 주의해서 사용해야 한다.
- 코틀린의 시퀀스는 코틀린/JVM, 코틀린/JS, 코틀린/네이티브 등의 일반적인 모듈에서 모두 사용할 수 있다. 하지만 자바 스트림은 코틀린/JVM에서만 동작하며, 그것도 JVM이 8버전 이상일 때만 동작한다.

병렬 모드로 성능적 이득을 얻을 수 있는 곳 → 자바 스트림
이외의 일반적인 경우 → 코틀린 시퀀스
