### ISSUE TITLE
Item 5. 예외를 활용해 코드에 제한을 걸어라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#5]
`Item 5. 예외를 활용해 코드에 제한을 걸어라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by aegis1920** [comment]
### 기본 라이브러리에 있는 함수를 활용해 제한을 걸어서 코드 자체적으로 검사가 될 수 있도록 하자

- require
  - argument를 검증
  - IllegalArgumentException를 throw
  - 가급적 초기화할 때 바로 검사해도 좋겠다.

<img width="541" alt="image" src="https://github.com/Meet-Coder-Study/effective-kotlin-study/assets/22311557/182eb0f4-adf8-49db-9ba6-0147ae196160">

- check
  - state를 검증
  - IllegalStateException를 throw
- assert
  - 테스트에만 적용된다
- nullability
  - ?: 활용
    - 함수를 중지시킬 수 있다. (?: run { "~~해서 중지됨" })
  - requireNotNull 활용
  - checkNotNull 활용
  - 위 함수 적용 이후 스마트 캐스트가 자동 지원됨

### 내 생각

- 실무에서 require, check, assert 등등.. 기본 라이브러리에 있는 함수들을 활용하는 곳이 있을지?
- 안 쓰고 있었다면 왜 안 쓰고 있었을까? 예외 처리의 불편함?
- assert는 왜 쓸까? assertThat만 쓰면 안 되나?
- 스마트 캐스트는 좋은 것 같음

**Comment by pkch93** [comment]
**_예외를 활용해 코드에 제한을 걸자_**

예외를 활용해 제한을 걸면 다음과 같은 장점이 존재한다.

- 문서를 읽지 않은 개발자도 문제를 확인할 수 있다.
- 예상하지 못한 동작을 막고 예외를 throw 하여 시스템을 안정적으로 유지할 수 있다.
- 코드가 자체적으로 검사된다.
- 스마트 캐스트 기능을 활용할 수 있어 타입 캐스트를 줄일 수 있다.

코틀린에서는 예외를 통한 제한을 위해 다음과 같은 API를 제공한다.

- require
    
    보통 인자의 유효성을 체크하는 데 사용한다. 따라서 위반되는 경우 IllegalArgumentException을 던진다.
    
- check
    
    상태 관련한 동작을 제한하는 데 사용한다. 따라서 위반되는 경우 IllegalStateException을 던진다.
    
- assert
    
    테스트 모드에서만 동작하며 어떤 것이 true 인지 확인하는데 사용한다.
    
- return이나 throw와 함께 사용하는 elvis 연산자
    
    참고로 elvis 연산자에서 return을 하면 함수를 바로 종료시킬 수 있다.

```kotlin
fun vaildNewUser(user: User) {
	user ?: return // 함수 종료
	// ...
}
```

> 예외를 사용해서 제한을 거는 방식은 어느 프로그래밍 언어에서나 통용되는 이야기라고 생각한다.
> 
> 여기서는 require, check의 코틀린 API가 코드 유효성 검사를 위해 사용할 수 있다는 것을 알게된 게 좋았다.

**Comment by cmg1411** [comment]
## require
- 인자를 검사하는데 사용
- IllegalArgumentException 을 던진다.
- 인자 유효성 검증이므로 보통 코드의 앞단에 위치하고 해야한다.
- 문서에 관련 내용을 명시해야한다.

## check
- 상태를 검사하는데 사용
- IllegalStateException 을 던진다.
- 규약을 어기고 사용하면 안되는 곳에서 함수를 사용하는 것을 막기 위해 사용.
- 보통 require 보다는 뒤에 위치

## assert
- 프로덕션 코드에 위치하지만, 테스트에서만 동작한다.
- `-ea` JVM 옵션을 활성화해야 한다.
- 프로덕션 코드에 위치하므로, 모든 테스트 케이스에서 공통적으로 assert 할 수 있다는 장점이 있다.
- 단, 실제 애플리케이션에서는 동작하지 않으므로 check 를 더 많이 쓰도록 하자.

## nullability 와 스마트 캐스팅
스마트 캐스팅
```kotlin
open class Outfit
class Dress : Outfit()
의 상속구조를 가졌을 때

class Person(
  val outfit: Outfit
)

require(person.outfit is Dress)
이후 person.outfit 은 Dress 타입이 된다.
```

null 도 마찬가지로

```kotlin
person.outfit 이 nullable 이라고 하면

require(person.outfit != null) // 또는 requireNotNull(person.outfit) 또는 checkNotNull(person.outfit)
이후 person.outfit 은 !! 없이 not null 로 쓸 수 있다.
```
