### ISSUE TITLE
Item 50. 컬렉션 처리 단계의 수를 제한하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#50]
`Item 50. 컬렉션 처리 단계의 수를 제한하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
모든 컬렉션 처리 메서드는 비용이 많이 든다. 내부적으로 요소들을 반복해 돌고 계산을 위해서 추가적인 컬렉션을 만들어내기 때문이다. Sequence도 마찬가지로 Sequence 전체를 래핑하는 객체가 만들어지며 조작을 위해 추가적인 객체를 만들어낸다. 따라서 요소가 많다면 꽤 큰 비용이 들어간다.

때문에 컬렉션으로 처리할 때 단계 수를 최대한 줄이는 것이 좋다.

```kotlin
fun List<Person>.getNames(): List<String> =
	this.map { it.name }
			.filter { it != null }
			.map { it!! }
```

위 코드는 3번의 단계를 돈다. 따라서 2000만의 요소를 가지는 List라면 각 단계를 200만개씩 돌 것이다. 때문에 단계수를 줄일 수 있다면 줄이는 것이 좋다.

```kotlin
// 좋음
fun List<Person>.getNames(): List<String> =	this.map { it.name }.filterNotNull()

// 가장 좋음.
fun List<Person>.getNames(): List<String> =	this.mapNotNull { it.name }
```

사실 컬렉션 처리와 관련해서 어떤 API가 있는지 모르는 경우가 많아 비효율적인 코드를 짜는 경우가 많다. 따라서 컬렉션에 어떤 메서드가 있는지 먼저 확인해보는 것이 좋다.

**Comment by rockjoon** [comment]
# item 50 컬렉션 처리 단계 수를 제한하라.

시퀀스 처리는 시퀀스에 대한 데코레이터 객체와 랩핑하는 객체가 생성되므로 비용이 소모되는 작업이다.  
따라서 가능한한 연산 단계를 낮추는 것이 좋다.

>표준 라이브러리를 공부하고 잘 숙지하자!

**Comment by hyenny** [comment]
### 두 단계 이상의 컬렉션 처리 함수를 한번에 끝내는 방법


이 코드 보다는 | 이 코드가 좋습니다
-- | --
.filter { it ≠ null } |  
.map {  it!! } | .filterNotNull()
.map {  <Transformation>} |  
.filterNotNull() | .mapNotNull { <Transformation>  }
.map { <Transformation> } |  
.joinToString() | .joinToString { <Transformation> }
.filter { <Predicate 1> } |  
.filter { <Predicate 1> } | .filter { Predicate 1 && Predicate2 } |  
.listOf(…) |  
.filterNotNull() | .listOfNotNull(…)


### 정리
컬렉션 처리 단계에서 '전체 컬렉션에 대한 반복'과 '중간 컬렉션 생성'이라는 비용이 발생한다. 이걸 조금이라도 줄이려면 한 번에 처리할 수 있는 표준 함수를 숙지해 사용하는 것이 좋다.
