### ISSUE TITLE
Item 51. 성능이 중요한 부분에는 기본 자료형 배열을 사용하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#51]
`Item 51. 성능이 중요한 부분에는 기본 자료형 배열을 사용하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
기본 자료형은 가볍고 빠르다. 때문에 대규모의 데이터 처리에는 기본 자료형을 사용하면 상당한 최적화가 이뤄진다. 단, List, Set과 같은 컬렉션은 제네릭을 사용하므로 기본 자료형을 사용할 수 없다. 따라서 성능이 중요한 경우에는 배열을 사용하는 것이 좋다.

> Kotlin/JVM에서 100만개의 Int를 `IntArray`와 `List<Int>`를 사용해서 비교했을때 메모리 공간 차지하는 것은 각각 400,000,016바이트, 2,000,006,944 바이트를 차지하므로 메모리만 보더라도 컬렉션이 5배 더 많은 공간을 차지한다. 또한 성능적으로도 평균을 구하는 연산에서 배열이 25% 가량 더 좋다.
>

**Comment by rockjoon** [comment]
# item 51 성능이 중요한 부분에는 기본 자료형 배열을 사용하라.

성능 : 기본형 배열 > 제네릭 콜렉션  
사용성 : 기본형 배열 < 제네릭 콜렉션  

따라서 일반적으로는 콜렉션을 사용하는 것이 무난하지만 성능이 중요한 이슈일 때는 기본형 배열이 좋다.

**Comment by hyenny** [comment]
### 기본 자료형의 특징
- 가볍다. 일반적인 객체와 다르게 추가적으로 포함되는 것들이 없기 때문
- 빠르다. 값에 접근할 때 추가 비용이 들어가지 않는다.
=> 대규모 데이터 처리할 때 기본 자료형 사용시 큰 최적화가 이루어짐

### 기본 자료형은 언제, List는 언제 사용?
기본 자료형을 포함한 배열은 코드 성능이 중요한 부분을 최적화할 때 활용하면 좋다.
배열은 더 적은 메모리를 차지하고, 더 빠르게 동작한다.
(=> 라이브러리 개발자, 게임 개발자, 고급 그래픽을 처리해야 하는 개발자)

다만 일반적인 경우에는 LIst를 사용하는 것이 좋음. List가 훨씬 더 기능이 다양하며, 더 많은 곳에 쉽게 사용될 수 있다.
