### ISSUE TITLE
Item 52. mutable 컬렉션 사용을 고려하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#52]
`Item 52. mutable 컬렉션 사용을 고려하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by pkch93** [comment]
컬렉션 복제 처리는 비용이 굉장히 많이 든다. 따라서 복제처리를 하지 않고 컬렉션을 조작할 수 있는 mutable 컬렉션이 성능적으로는 더 좋다. 또한 지역 변수로 사용하는 경우라면 mutable 컬렉션이 더 합리적이라고 할 수 있다. 때문에 코틀린 표준 라이브러리에서도 내부적으로 어떤 처리를 할 때는 mutable 컬렉션을 사용하도록 구현되어있다.

개인적으로는 클래스에 상태값으로 컬렉션을 사용할 때는 매우 큰 컬렉션을 사용하는 경우가 아니라면 immutable이 주는 이점을 포기할 이유는 없어보인다. 지역 변수 같이 지협적으로 사용하거나 성능적으로 필요한 경우에만 mutable 컬렉션 사용을 고려해보면 되지 않을까 생각한다.

**Comment by rockjoon** [comment]
# item 52 mutable 컬렉션 사용을 고려하라.

객체 생성 비용을 가늠하는 것은 항상 어려운 것 같다. 순수 함수형 프로그래밍에서는 모든 객체(컬렉션 포함)가 immutable이다.
함수형 프로그래밍에서 성능을 전혀 고려하지 않기 때문이라기 보다는 객체 생성 비용을 그렇게 크리티컬하게 보지 않기 때문이다.  
하지만 객체(혹은 컬렉션)가 매우 무거운 경우라면 또 얘기가 달라질 것이다. 결국 이 또한 진리의 케바케인 것인가...?

**Comment by hyenny** [comment]
- 가변 컬렉션은 일반적으로 **추가 처리가 빠르다.**
- immutable 컬렉션은 컬렉션 변경과 관련된 처리를 더 세부적으로 조정할 수 있다. 안전하다.

일반적으로 지역 스코프에서는 이러한 세부적인 조정이 필요하지 않으므로, 가변 컬렉션을 사용하는 것이 좋다. -> 스코프 적게, 지역 변수에서 mutable 컬렉션 사용해서 연산하고 immutable로 반환하면 될 듯
