### ISSUE TITLE
Item 6. 사용자 정의 오류보다는 표준 오류를 사용하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#6]
`Item 6. 사용자 정의 오류보다는 표준 오류를 사용하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by aegis1920** [comment]
### 내 생각

- 제목이 곧 내용뿐
- 다른 분들도 표준 오류를 많이 사용하는지? 기준이 있는지 궁금
  - 많이 쓰는 표준오류 참고 : https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/jvm/runtime/kotlin/TypeAliases.kt

**Comment by pkch93** [comment]
**_사용자 정의 오류보다는 표준 오류를 사용하라_**

require, check, assert 함수를 사용하면 대부분의 Kotlin에서 발생하는 오류를 처리할 수 있다. 하지만 이외에 예상하지 못한 예외가 발생할 수 있다. 이때 직접 예외를 정의하는 것보다는 최대한 표준 라이브러리의 예외를 사용하는 것을 권장한다. 표준 예외를 사용하면 다른 사람들이 API를 더 쉽게 배우고 이해할 수 있기 때문이다.

> Effective Java 3/E의 `item 72. 표준 예외를 사용하라`의 사실상 코틀린 버전... (사실 이 item을 Effective Java 3/E로 옮겨도 무방하지 않을까..)

**Comment by cmg1411** [comment]
사용자 정의 예외를 사용해야하는 상황이 너무나 많지 않을까?
