### ISSUE TITLE
Item 7. 결과 부족이 발생할 경우 null과 Failure를 사용하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#7]
`Item 7. 결과 부족이 발생할 경우 null과 Failure를 사용하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by aegis1920** [comment]
### 예측할 수 있는 범위의 오류는 null과 Failure를 사용하고, 예측하기 어려운 범위의 오류는 예외를 throw하자

- 예외는 정보를 전달하는 방법으로 사용해서는 안 된다
  - 많은 개발자가 예외가 전파되는 과정을 제대로 추적하지 못한다
  - 코틀린의 모든 예외는 unchecked다
  - try catch 블록 내부에 코드를 배치하면 컴파일러가 할 수 있는 최적화가 제한된다
- null을 사용한 뒤, ?:를 통해 안전하게 처리하자
- Result와 같은 공용체 타입(Success, Failure)을 만든 뒤, when을 통해 처리하자
  - 정말 명시적일듯
  - Failure는 처리할 때 필요한 정보를 가질 수 있다

### API 개발 시 가급적 null을 리턴할 수 있는 경우까지 고려해서 개발하자

- e.g. List의 get(), getOrNull()
- getOrNull()을 만들어서 null 처리를 개발자에게 맡길 수 있도록

### 내 생각

- 가급적 명시적으로 작성하도록 노력하기 (응답의 경우, Success와 Fail 밖에 없으니 두 타입만 가지는 클래스 생성)
- API 개발 시 null을 고려해서 작성

**Comment by pkch93** [comment]
**_예외는 정보를 전달하는 방법으로 사용하면 안된다._**

함수가 원하는 결과를 만들지 못하는 경우가 있다. 이런 상황을 처리하는 메커니즘으로는 크게 두 가지 방법이 있다.
- null이나 실패를 담당하는 클래스 반환
- 예외 처리

이때 예외 처리하는 방식은 정보를 전달하는 방법으로 사용해서는 안된다. 잘못된 상황을 처리하는데 사용해야하며 그렇지 않으면 다음과 같은 문제가 발생한다.

- 예외가 전파되는 과정 추적에 혼동이 생김
- Kotlin의 모든 예외는 unchecked 예외이다. 때문에 사용자가 예외처리하지 않을 수도 있으며 때문에 파악이 힘들어 질 수 있다.
- try-catch 블록 내부에 코드를 배치하면 컴파일러 최적화에 제한이 생길 수 있다.

**_결과 부족은 null이나 Failure 같은 별도 객체를 사용해라._**

null과 Failure로 예상되는 오류를 표현하면 명시적이고 효율적이며 간단히 처리가능하다.

```kotlin
inline fun <reified T> String.readObjectOrNull(): T? {
	// ...
	if (incorrectSign) {
		return null
	}
	// ...
	return result
}

inline fun <reified T> String.readObject(): Result<T> {
	// ...
	if (incorrectSign) {
		throw Failure(JsonParsingException())
	}
	// ...
	return Success(result)
}

sealed class Result<out T>
class Success<out T>(val result: T): Result<T>()
class Failure(val throwable: Throwable): Result<Nothing>()

class JsonParsingException: Exception()

```

위와 같이 명시적으로 성공/실패를 구분하여 가독성을 높일 수 있다. 이렇게 Result로 성공/실패를 표현하면 다음과 같이 when 표현식을 통해 처리가능하다.

```kotlin
val person = userText.readObjectOrNull<Person>()
val age = when(person) {
	is Success -> person.age
	is Failure -> -1
}
```

위와 같이 성공/실패에 따른 처리가 가능하다.

**Comment by cmg1411** [comment]
예외는 정보 전달에 쓰이면 안된다. 예외는 예외 상황에서만 쓰는게 좋다.
- 예외 전파 과정을 추적하기 어렵다
- 코틀린은 unchecked 예외이기에, 예외처리가 누락되기 쉽다.
- 명시적인 처리보다 예외처리가 느리다.
- try-catch 문 안의 코드는 컴파일러 최적화에 불리하다.

따라서, `예상되는 오류` 에는 `null` 또는 `sealed class 의 Faliure` 를 반환하자.

추가적인 정보를 전달해야하는 경우 -> Failure 반환
아니면 -> null 반환

리턴타입을 보통 제한하므로 null 을 반환하는것이 공통적인 처리에 좋아 보인다.

List 에는 예외를 터뜨리는 경우와 null 을 반환하는 경우가 모두 있다.
- get() : 인덱스를 벗어난 경우 IndexBoundOutOfException
- getOrNull() : 인덱스를 벗어난 경우 null 반환

인덱스를 벗어난 경우가 있을 것 같은 상황이면 getOrNull,
인덱스를 벗어난 경우가 있으면 안되면 get 을 쓰도록 하자.

---

JPA 에도
`fun <T, ID> CrudRepository<T, ID>.findByIdOrNull(id: ID): T? = findById(id).orElse(null)` 같은게 있어서 활용하기 좋습니다
