### ISSUE TITLE
Item 8. 적절하게 null을 처리하라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#8]
`Item 8. 적절하게 null을 처리하라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by aegis1920** [comment]
### null을 적절하게 처리하자

- ?., 스마트 캐스팅, ?: 활용
- 미래에 코드가 어떻게 변화할 지 모르니 !!는 쓰지 않기
  - lateinit 또는 Delegates.notNull을 활용하자

**Comment by pkch93** [comment]
**_null은 중의적인 의미를 가진다._**

null은 값이 부족하다를 의미한다. 따라서, null로 설정되어 있다는 의미는 **값이 설정되지 않았거나**, **제거되었다는 것**을 의미한다. 때문에 null을 반환한다는 의미는 여러 의미를 가질 수 있다.

여러 의미를 갖는다는 것은 코드를 유지보수하기 어렵게 만드므로 `String#toIntOrNull`이나 `Interable<T>.firstOrNull`과 같이 명확한 의미를 갖도록 하는 것이 좋다. 명확하게 만들어야 하는 이유는 nullable 값을 처리해야 하기 때문이다.

기본적으로 Kotlin에서 `nullable` 타입은 다음과 같이 처리한다.

- ?., 스마트 캐스팅, elvis 연산자
- 오류를 throw
- 함수 또는 프로퍼티를 리펙터링하여 nullable이 되지 않도록 변경

**_not null assertion을 남용하지는 말자_**

`!!`을 사용하는 것은 Java에서 nullable 값을 처리할 때 발생할 수 있는 문제가 똑같이 발생한다. 즉, `!!`을 사용한 대상이 null인 경우 NPE가 발생한다.

보통 `!!`은 nullable 타입이지만 null이 되지 않는다고 확신하는 경우에 많이 사용된다. 하지만, 이 부분에서 미래에도 null이 되지 않는다고 확신할 수는 없다. 따라서 `!!`를 사용하거나 명시적으로 예외를 던지는 형식으로 설계하는 미래에 해당 코드가 오류를 발생시킬 수 있다는 것을 염두해야한다. 이 경우에도 `!!`는 제한된 정보만을 제공해주기 때문에 명시적으로 예외를 던지는 편이 더 좋은 방법이다.

이런 이유로 `!!` 연산자를 사용하는 것을 제한해야하며 nullability가 제대로 표현되지 않는 라이브러리를 사용할 때 정도만 사용해야한다.

> 라이브러리의 프로퍼티가 null이 될 수 없는 프로퍼티임에도 nullable로 표현되는 경우 등에 대해 사용하라는 의미로 보인다.

**_의미 없는 nullability 피하기_**

의미 없는 nullable은 불필요한 예외 처리를 야기하며 최악의 경우 `!!` 연산자의 남용을 유발한다. 따라서 null을 피하는 방법을 사용할 것을 추천한다.

- 컬렉션의 경우 null보다는 빈 컬렉션 반환한다.
- nullable enum과 None enum은 완전히 다른 의미이다. None enum을 사용할 것.

**lateinit 프로퍼티와 notNull delegate**

클래스 이후에 확실히 생성이 보장되는 경우 lateinit과 notNull delegate를 사용할 것을 권장한다. lateinit은 프로퍼티가 이후에 설정될 것을 명시하는 한정자로 다음과 같은 이점이 있다.

- `!!` 연산자로 nullability를 처리할 필요가 없다.
- 이후에 어떤 의미를 나타내기 위해 nullable로 만들 수 있다.
- 초기화 이후에는 초기화되지 않은 상태로 돌아갈 수 없다.

단, 초기화 되지 않은 상태에서 lateinit 프로퍼티를 사용하면 예외가 발생한다. 그리고 Int, Long, Double, Boolean과 같은 기본 타입과 연결된 타입으로 프로퍼티를 초기화하는 경우에는 lateinit을 사용할 수 없다.

이 경우에는 `Delegates#notNull`을 사용해야한다.

```kotlin
private var id: Int by Delegates.notNull()
```

위와 같이 프로퍼티 위임을 사용하여 nullability로 발생하는 문제점을 해결할 수 있다.

**Comment by cmg1411** [comment]
### null 안전 처리
1. 스마트 캐스팅 : if (printer != null) printer.print() else null
2. Elvis : printer?.print() ?: null

### 많은 객체가 null 관련 처리를 지원한다.
1. List -> 컬렉션같은 경우는 값이 없으면 emptyList() 같은걸 반환하길 바란다.
```
var list: List<Int>
val a = list.orEmpty()
```
2. String.toIntOrNull()
3. Iterable<T>.firtOrNull(() -> Boolean)


### !! assertion
printer?.print() 는 printer 가 null 이면 print 를 실행하지 않고 그냥 넘어간다.
놓칠 수 있다는 말.

nullable 프로퍼티이지만 당연히 notnull 일거라 생각되는 상황에
`!!` 를 붙여서 에러를 터뜨려줄 수 있다.
또는 다음과 같은 방법이 있다.
- printer!!.print()
- printer?.print() ?: throw ~
- requireNotNull(printer); printer.print()
- checkNotNull(printer); printer.print()


### !! 쓰지 말기
!! 는 자바의 NPE 와 같은 문제를 발생시킨다.
`일반적인 코틀린 프로그래밍에서는 !! 를 쓸 일이 없어야한다` 라고 강하게 말하고 있다.

대안은 lateinit, Delegates.notNull
