### ISSUE TITLE
Item 9. use를 사용하여 리소스를 닫아라

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/effective-kotlin-study#9]
`Item 9. use를 사용하여 리소스를 닫아라`를 학습하고 요약 및 근거들을 남겨주세요.

**Comment by aegis1920** [comment]
### use를 사용해서 Closable/AutoCloseable을 구현한 객체를 쉽고 안전하게 처리하자

- 제목이 곧 내용
- 파일을 한 줄씩 처리한다면 useLines도 활용할 수 있다

**Comment by pkch93** [comment]
**_코틀린에서는 Closable 객체 정리를 위한 use 함수를 지원한다._**

더 이상 리소스를 필요로하지 않을때 close로 명시적으로 닫아야하는 리소스가 있다. 특히 코틀린/JVM에서 사용하는 Java 표준 라이브러리에 InputStream/OutputStream, Connection, Reader, Socket 등 이런 리소스들이 많다.

이런 모든 리소스는 최종적으로 리소스에 대한 레퍼런스가 없어질 때 GC를 통해 처리된다. 하지만 굉장히 느리며 리소스를 처리하는 비용이 많이 들어간다. 따라서 더이상 사용되지 않을때 반드시 close를 사용하여 리소스를 명시적으로 닫아야한다.

이때 try-finally 구문은 굉장히 복잡하며 finally에서 리소스를 닫을때도 예외가 발생할 수 있다. 즉, 리소스를 닫을때의 예외도 처리해야한다. 이는 굉장히 귀찮고 복잡한 구문을 만든다.

이를 편하게 제공하기 위해 코틀린은 `use` 함수를 제공한다. 사용하고자 하는 리소스에 `use`를 사용하면 원하는 동작 후 리소스를 닫는다.

```kotlin
fun fileLinecount(path: String): Int {
	val reader = BufferedReader(FileReader(path)
	reader.use { return reader.lineSequence().sumBy { it.length } }
}
```

`use` 외에도 파일을 한 줄씩 읽는 `useLines` 등 다양한 `use` 함수가 존재한다. 이런 `use` 함수는 모든 `Closeable` 객체에 사용할 수 있다.
